global class RecordTypes {
	//Last update: 2019-10-15 12:45:45

	//Account
	global static final String Account_Efector = 'Account-Efector';
	global static final String Account_Asociado = 'Account-Asociado';

	//Knowledgekav
	global static final String Knowledgekav_FAQ = 'Knowledge__kav-FAQ';
	global static final String Knowledgekav_Procedimiento = 'Knowledge__kav-Procedimiento';
	global static final String Knowledgekav_OrientacionalAgente = 'Knowledge__kav-Orientacion_al_Agente';

	//Case
	global static final String Case_Autorizaciondeprestaciones = 'Case-Autorizacion_de_prestaciones';
	global static final String Case_Consultas = 'Case-Consultas';
	global static final String Case_Reclamos = 'Case-Reclamos';
	global static final String Case_Casoatipificar = 'Case-Caso_a_tipificar';

	//Eventomedico
	global static final String Eventomedico_Eventomedicodeseguimiento = 'Evento_medico__c-Evento_medico_de_seguimiento';
	global static final String Eventomedico_Eventomedicodeinternacion = 'Evento_medico__c-Evento_medico_de_internacion';
}