public class WSAsociadoGetClausulasPlanMock  {

	public static String getFound(){
		return
			'{' +
				'"data": [' +
					'{' +
						'"fecha_vigencia_desde": "1900-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "BAS",' +
						'"nombre": "CUOTA BASICA",' +
						'"caracteristica": "Base",' +
						'"contratada": "V",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Permanente"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "1900-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "C ORT",' +
						'"nombre": "COBERTURA DE ORTODONCIA",' +
						'"caracteristica": "Base",' +
						'"contratada": "V",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Permanente"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "2009-04-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "COB_ECCO",' +
						'"nombre": "ECCO ADICIONAL",' +
						'"caracteristica": "Base",' +
						'"contratada": "V",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Temporaria"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "2006-11-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "COB_LIMITROFES",' +
						'"nombre": "COBERTURA PAISES LIMITROFES",' +
						'"caracteristica": "Opcional",' +
						'"contratada": "F",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Temporaria"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "2013-10-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "CS_HERCULES",' +
						'"nombre": "CUOTA SOCIAL HERCULES",' +
						'"caracteristica": "Opcional",' +
						'"contratada": "F",' +
						'"informa": "V",' +
						'"bonificable": "V",' +
						'"permanente": "Permanente"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "1900-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "C_MED",' +
						'"nombre": "COBERTURA MEDICAMENTOS",' +
						'"caracteristica": "Base",' +
						'"contratada": "V",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Permanente"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "1900-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "C_OPT",' +
						'"nombre": "COBERTURA OPTICA",' +
						'"caracteristica": "Base",' +
						'"contratada": "V",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Permanente"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "2000-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "C_OS",' +
						'"nombre": "COBERTURA A CARGO OBRA SOCIAL EN EMPRESAS",' +
						'"caracteristica": "Base",' +
						'"contratada": "V",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Permanente"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "1900-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "C_PMI-HIJO",' +
						'"nombre": "COBERTURA PMI PARA HIJOS",' +
						'"caracteristica": "Base",' +
						'"contratada": "V",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Temporaria"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "2000-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "C_PMI-MADRE",' +
						'"nombre": "COBERTURA PMI PARA MADRES",' +
						'"caracteristica": "Base",' +
						'"contratada": "V",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Temporaria"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "2000-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "EME",' +
						'"nombre": "Emergencias Médicas Extra",' +
						'"caracteristica": "Opcional",' +
						'"contratada": "F",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Permanente"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "2000-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "HPR",' +
						'"nombre": "Habitación privada en Internación",' +
						'"caracteristica": "Opcional",' +
						'"contratada": "F",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Permanente"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "1900-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "PMI",' +
						'"nombre": "Plan Materno Infantil",' +
						'"caracteristica": "Opcional",' +
						'"contratada": "F",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Permanente"' +
					'},' +
					'{' +
						'"fecha_vigencia_desde": "2015-01-01",' +
						'"fecha_vigencia_hasta": null,' +
						'"codigo": "VACUNAS",' +
						'"nombre": "VACUNAS CALENDARIO",' +
						'"caracteristica": "Base",' +
						'"contratada": "V",' +
						'"informa": "F",' +
						'"bonificable": "V",' +
						'"permanente": "Permanente"' +
					'}' +
				'],' +
				'"meta": {' +
					'"allowed_filters": [],' +
					'"allowed_sorts": [],' +
					'"allowed_appends": [],' +
					'"allowed_fields": [],' +
					'"allowed_includes": [],' +
					'"default_includes": [],' +
					'"optional_get_vars": {' +
						'"sortBy": [],' +
						'"sortOrder": [' +
							'"asc",' +
							'"desc"' +
						'],' +
						'"pageSize": {' +
							'"0": "?pageSize=0",' +
							'"15": "?pageSize=15",' +
							'"50": "?pageSize=50",' +
							'"100": "?pageSize=100"' +
						'}' +
					'}' +
				'}' +
			'}';
	}

	public static String getError() {
		return
			'{' +
				'"data": {' +
					'"error": true,' +
					'"errors": [],' +
					'"errorType": "exception",' +
					'"httpCode": 404,' +
					'"message": "La ruta que está buscando no existe.",' +
					'"debug_message": [],' +
					'"exception": "NotFoundHttpException",' +
					'"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteCollection.php",' +
					'"line": 179' +
				'}' +
			'}';
	}
}