public class WSAsociadoGetAlertasMock  {
	public static String getFound(){
		return
			'{' +
				'"data": {' +
					'"checks": [' +
						'{' +
							'"Fecha_Desde": "15/01/2019",' +
							'"Fecha_Hasta": "",' +
							'"Codigo": "ALERTA_AUDIT_PREV",' +
							'"Nombre": "ALERTA AUDITORIA PREVIA",' +
							'"Individual": "F",' +
							'"Familia": "V",' +
							'"Empresa": "F",' +
							'"OOSS": "F",' +
							'"Referencia": "2"' +
						'},' +
						'{' +
							'"Fecha_Desde": "15/01/2019",' +
							'"Fecha_Hasta": "",' +
							'"Codigo": "ALERTA_AUDIT_REIN",' +
							'"Nombre": "ALERTA AUDITORIA EN REINTEGROS",' +
							'"Individual": "F",' +
							'"Familia": "V",' +
							'"Empresa": "F",' +
							'"OOSS": "F",' +
							'"Referencia": "2"' +
						'}' +
					'],' +
					'"alertas": [' +
						'{' +
							'"Fecha_Desde": "13/09/2018",' +
							'"Fecha_Hasta": "",' +
							'"Codigo": "CUOTAS_1",' +
							'"Nombre": "CUOTAS ADEUDADAS 1 (ACA)",' +
							'"Individual": "F",' +
							'"Familia": "V",' +
							'"Empresa": "F",' +
							'"OOSS": "F",' +
							'"Id_Alerta": "4879269"' +
						'},' +
						'{' +
							'"Fecha_Desde": "15/01/2019",' +
							'"Fecha_Hasta": "",' +
							'"Codigo": "CUOTAS_2",' +
							'"Nombre": "CUOTAS ADEUDADAS 2 (ACA)",' +
							'"Individual": "F",' +
							'"Familia": "V",' +
							'"Empresa": "F",' +
							'"OOSS": "F",' +
							'"Id_Alerta": "5027003"' +
						'}' +
					']' +
				'}' +
			'}';
	}
}