public class WSAsociadoGetTopesMock  {

	public static String getFound(){
		return
			'{' +
			  '"data": [' +
					'{' +
						  '"rubro_tope": "ALERGIA TESTIFICACION",' +
						  '"tope": "TOPE DE 1 POR AÑO",' +
						  '"clausula": "CUOTA BASICA",' +
						  '"valor_tope": "1",' +
						  '"consumo": "0",' +
						  '"remanente": "1",' +
						  '"valor_red": null,' +
						  '"remanente_red": null,' +
						  '"nombre_red": null,' +
						  '"contexto": "A",' +
						  '"sistema": "*",' +
						  '"aplicacion": "A",' +
						  '"tipo_valor": "C",' +
						  '"periodo": "A",' +
						  '"base_calculo_2": "I",' +
						  '"tocmpc_id": "1500",' +
						  '"tocpc_id": null,' +
						  '"afi_id": "180015",' +
						  '"fecha": "2019-12-15",' +
						  '"codi_claus": "BAS",' +
						  '"tope_id": "M"' +
					'},' +
					'{' +
						  '"rubro_tope": "PSICOTERAPIA",' +
						  '"tope": "TOPE DE 1 POR AÑO",' +
						  '"clausula": "CUOTA BASICA",' +
						  '"valor_tope": "1",' +
						  '"consumo": "0",' +
						  '"remanente": "1",' +
						  '"valor_red": null,' +
						  '"remanente_red": null,' +
						  '"nombre_red": null,' +
						  '"contexto": "A",' +
						  '"sistema": "*",' +
						  '"aplicacion": "A",' +
						  '"tipo_valor": "C",' +
						  '"periodo": "A",' +
						  '"base_calculo_2": "I",' +
						  '"tocmpc_id": "1501",' +
						  '"tocpc_id": null,' +
						  '"afi_id": "180015",' +
						  '"fecha": "2019-12-15",' +
						  '"codi_claus": "BAS",' +
						  '"tope_id": "M"' +
					'},' +
					'{' +
						  '"rubro_tope": "PSICOTERAPIA",' +
						  '"tope": "TOPE DE 1 POR AÑO",' +
						  '"clausula": "CUOTA BASICA",' +
						  '"valor_tope": "1",' +
						  '"consumo": "0",' +
						  '"remanente": "1",' +
						  '"valor_red": null,' +
						  '"remanente_red": null,' +
						  '"nombre_red": null,' +
						  '"contexto": "A",' +
						  '"sistema": "*",' +
						  '"aplicacion": "A",' +
						  '"tipo_valor": "C",' +
						  '"periodo": "A",' +
						  '"base_calculo_2": "I",' +
						  '"tocmpc_id": "1783",' +
						  '"tocpc_id": null,' +
						  '"afi_id": "180015",' +
						  '"fecha": "2019-12-15",' +
						  '"codi_claus": "BAS",' +
						  '"tope_id": "M"' +
					'},' +
					'{' +
						  '"rubro_tope": "PSICOTERAPIA",' +
						  '"tope": "TOPE DE 1 POR AÑO",' +
						  '"clausula": "CUOTA BASICA",' +
						  '"valor_tope": "1",' +
						  '"consumo": "0",' +
						  '"remanente": "1",' +
						  '"valor_red": null,' +
						  '"remanente_red": null,' +
						  '"nombre_red": null,' +
						  '"contexto": "A",' +
						  '"sistema": "*",' +
						  '"aplicacion": "A",' +
						  '"tipo_valor": "C",' +
						  '"periodo": "A",' +
						  '"base_calculo_2": "I",' +
						  '"tocmpc_id": "1784",' +
						  '"tocpc_id": null,' +
						  '"afi_id": "180015",' +
						  '"fecha": "2019-12-15",' +
						  '"codi_claus": "BAS",' +
						  '"tope_id": "M"' +
					'},' +
					'{' +
						  '"rubro_tope": "GOTEO PSICOFARMACOS",' +
						  '"tope": "TOPE DE 1 POR MES",' +
						  '"clausula": "CUOTA BASICA",' +
						  '"valor_tope": "1",' +
						  '"consumo": "0",' +
						  '"remanente": "1",' +
						  '"valor_red": null,' +
						  '"remanente_red": null,' +
						  '"nombre_red": null,' +
						  '"contexto": "A",' +
						  '"sistema": "*",' +
						  '"aplicacion": "A",' +
						  '"tipo_valor": "C",' +
						  '"periodo": "M",' +
						  '"base_calculo_2": "I",' +
						  '"tocmpc_id": "1502",' +
						  '"tocpc_id": null,' +
						  '"afi_id": "180015",' +
						  '"fecha": "2019-12-15",' +
						  '"codi_claus": "BAS",' +
						  '"tope_id": "M"' +
					'},' +
					'{' +
						  '"rubro_tope": "CONSULTA PSIQUIATRICA",' +
						  '"tope": "TOPE DE 1 POR MES",' +
						  '"clausula": "CUOTA BASICA",' +
						  '"valor_tope": "1",' +
						  '"consumo": "0",' +
						  '"remanente": "1",' +
						  '"valor_red": null,' +
						  '"remanente_red": null,' +
						  '"nombre_red": null,' +
						  '"contexto": "A",' +
						  '"sistema": "*",' +
						  '"aplicacion": "A",' +
						  '"tipo_valor": "C",' +
						  '"periodo": "M",' +
						  '"base_calculo_2": "I",' +
						  '"tocmpc_id": "1503",' +
						  '"tocpc_id": null,' +
						  '"afi_id": "180015",' +
						  '"fecha": "2019-12-15",' +
						  '"codi_claus": "BAS",' +
						  '"tope_id": "M"' +
					'},' +
					'{' +
						  '"rubro_tope": "LINFEDEMA",' +
						  '"tope": "TOPE DE 1 POR MES",' +
						  '"clausula": "CUOTA BASICA",' +
						  '"valor_tope": "1",' +
						  '"consumo": "0",' +
						  '"remanente": "1",' +
						  '"valor_red": null,' +
						  '"remanente_red": null,' +
						  '"nombre_red": null,' +
						  '"contexto": "A",' +
						  '"sistema": "*",' +
						  '"aplicacion": "A",' +
						  '"tipo_valor": "C",' +
						  '"periodo": "M",' +
						  '"base_calculo_2": "I",' +
						  '"tocmpc_id": "1504",' +
						  '"tocpc_id": null,' +
						  '"afi_id": "180015",' +
						  '"fecha": "2019-12-15",' +
						  '"codi_claus": "BAS",' +
						  '"tope_id": "M"' +
					'},' +
					'{' +
						  '"rubro_tope": "ALERGIA TESTIFICACION",' +
						  '"tope": "TOPE DE 1 POR MES",' +
						  '"clausula": "CUOTA BASICA",' +
						  '"valor_tope": "1",' +
						  '"consumo": "0",' +
						  '"remanente": "1",' +
						  '"valor_red": null,' +
						  '"remanente_red": null,' +
						  '"nombre_red": null,' +
						  '"contexto": "A",' +
						  '"sistema": "*",' +
						  '"aplicacion": "A",' +
						  '"tipo_valor": "C",' +
						  '"periodo": "M",' +
						  '"base_calculo_2": "I",' +
						  '"tocmpc_id": "1505",' +
						  '"tocpc_id": null,' +
						  '"afi_id": "180015",' +
						  '"fecha": "2019-12-15",' +
						  '"codi_claus": "BAS",' +
						  '"tope_id": "M"' +
					'}' +
			  ']' +
		'}';
	}

	public static String getError(){
		return
			'{' +
				'"data": {' +
					'"error": true,' +
					'"errors": [],' +
					'"errorType": "exception",' +
					'"httpCode": 404,' +
					'"message": "El ID del Afiliado es inválido.",' +
					'"debug_message": [],' +
					'"exception": "NotFoundHttpException",' +
					'"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php",' +
					'"line": 964' +
				'}' +
			'}';
	}
}