public class WSAsociadoGetAportesDeclaradosMock  {

	public static String getFound(){
		return
			'{' +
				'"data": [' +
					'{' +
						'"dnad_id": "3482662",' +
						'"periodo": "2018-12-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "3850.52",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "3657.99",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 1003637,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "1003637",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "191485.89",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3453095",' +
						'"periodo": "2018-11-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "3652.16",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "3469.55",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 990464,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "990464",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "176828.63",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3423701",' +
						'"periodo": "2018-10-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "3534.35",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "3357.63",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 977249,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "977249",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "168848.21",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3392658",' +
						'"periodo": "2018-09-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "3367.07",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "3198.72",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 963501,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "963501",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "158424.79",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3363349",' +
						'"periodo": "2018-08-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "5511.11",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "5235.55",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 950533,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "950533",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "259208.62",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3335205",' +
						'"periodo": "2018-07-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "3367.07",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "3198.72",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 938298,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "938298",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "160492.84",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3304825",' +
						'"periodo": "2018-06-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "3367.07",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "3198.72",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 924708,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "924708",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "173790.78",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3276446",' +
						'"periodo": "2018-05-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "3062.91",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "2909.76",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 912532,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "912532",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "152948.86",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3247575",' +
						'"periodo": "2018-04-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "2552.43",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "2424.81",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 899929,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "899929",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "155826.76",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3219161",' +
						'"periodo": "2018-03-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "4288.08",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "4073.68",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 887464,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "887464",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "162071.18",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3190571",' +
						'"periodo": "2018-02-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "4645.41",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "4413.14",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 875081,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "875081",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "219646.02",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3162290",' +
						'"periodo": "2018-01-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "3062.91",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "2909.76",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 862881,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "862881",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "140462.32",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3133799",' +
						'"periodo": "2017-12-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "3047.24",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "2894.88",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 850666,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "850666",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "135753.92",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'},' +
					'{' +
						'"dnad_id": "3104092",' +
						'"periodo": "2017-11-01",' +
						'"cuit": "30604958640",' +
						'"empleador": "600011",' +
						'"nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"obra_social": "101604",' +
						'"codigo_obra_social": "640008",' +
						'"nombre_obra_social": "O.S.P.ACA",' +
						'"cuil": "20173909471",' +
						'"origen_aporte": "EST",' +
						'"remuneracion": "0",' +
						'"aporte": "3178.35",' +
						'"aporte_reconocido": null,' +
						'"aporte_derivado": "3019.43",' +
						'"secuencia": "0",' +
						'"adherentes": "0",' +
						'"familiares": "0",' +
						'"ad_id": 837811,' +
						'"para_cuota": null,' +
						'"para_fondo_reserva": null,' +
						'"secuencia_ad": "837811",' +
						'"origen_aporte_ad": "N/A",' +
						'"secuencia_nominal": "0",' +
						'"origen_aporte_nomi": "EST",' +
						'"total_aportes": "0",' +
						'"total_aportes_reconocidos": null,' +
						'"total_familiares": "0",' +
						'"total_remuneraciones": "0",' +
						'"total_aportes_derivados": null,' +
						'"total_adherentes": "0",' +
						'"total_aportes_nomi": "140295.88",' +
						'"total_aportes_reconocidos_nomi": null,' +
						'"total_familiares_nomi": "0",' +
						'"total_remuneracines_nomi": "0",' +
						'"total_aportes_derivados_nomi": null,' +
						'"total_adherentes_nomi": "0"' +
					'}' +
				'],' +
				'"meta": {' +
					'"allowed_filters": [],' +
					'"allowed_sorts": [],' +
					'"allowed_appends": [],' +
					'"allowed_fields": [],' +
					'"allowed_includes": [],' +
					'"default_includes": [],' +
					'"optional_get_vars": {' +
						'"sortBy": [],' +
						'"sortOrder": [' +
							'"asc",' +
							'"desc"' +
						'],' +
						'"pageSize": {' +
							'"0": "?pageSize=0",' +
							'"15": "?pageSize=15",' +
							'"50": "?pageSize=50",' +
							'"100": "?pageSize=100"' +
						'}' +
					'}' +
				'}' +
			'}';
	}

	public static String getError(){
		return
			'{' +
				'"data": {' +
					'"error": true,' +
					'"errors": [],' +
					'"errorType": "exception",' +
					'"httpCode": 404,' +
					'"message": "Código de Afiliado inválido.",' +
					'"debug_message": [],' +
					'"exception": "NotFoundHttpException",' +
					'"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php",' +
					'"line": 964' +
				'}' +
			'}';
	}
}