public class WSAsociadoGetConsumosMock  {

	public static String getFoundPaginated() {
		return 
            '{' +
                '"data": [' +
                    '{' +
                        '"rn": "1",' +
                        '"fecha_prestacion": "2018-11-06 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "25367",' +
                        '"desc_prestacion": "SINALGICO SL, 10 MG COMP.SUBL.X 10",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1013431967",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "0",' +
                        '"importe": "42.57",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "73899467",' +
                        '"origen": "Post"' +
                    '},' +
                    '{' +
                        '"rn": "2",' +
                        '"fecha_prestacion": "2018-11-06 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "10605",' +
                        '"desc_prestacion": "AMIXEN, 500 MG COMP.X 16",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1013431967",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "0",' +
                        '"importe": "29.45",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "73899466",' +
                        '"origen": "Post"' +
                    '},' +
                    '{' +
                        '"rn": "3",' +
                        '"fecha_prestacion": "2018-09-13 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "32116",' +
                        '"desc_prestacion": "POVIRAL, 800 MG COMP.X 20",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1013057258",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "756279",' +
                        '"efector_prescriptor": "ARDUSSO LEDIT RAMON FRANCISCO",' +
                        '"presentado": "0",' +
                        '"importe": "140.08",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "73818445",' +
                        '"origen": "Post"' +
                    '},' +
                    '{' +
                        '"rn": "4",' +
                        '"fecha_prestacion": "2018-10-04 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "33431",' +
                        '"desc_prestacion": "COLIXANE 200, COMP.X 30",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1013205851",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "759455",' +
                        '"efector_prescriptor": "GAMBA ARIEL ALEJANDRO",' +
                        '"presentado": "0",' +
                        '"importe": "47",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "73812992",' +
                        '"origen": "Post"' +
                    '},' +
                    '{' +
                        '"rn": "5",' +
                        '"fecha_prestacion": "2018-10-05 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1013248528",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": "874621",' +
                        '"efector_realizador": "DEMARIA JUAN PABLO",' +
                        '"prescriptor": null,' +
                        '"efector_prescriptor": null,' +
                        '"presentado": "336.7",' +
                        '"importe": "336.7",' +
                        '"presentacion": "218110765",' +
                        '"nro_factura": "6490",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7901",' +
                        '"lote": "815002",' +
                        '"renglones": "38024117",' +
                        '"pca_id": "73773192",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "6",' +
                        '"fecha_prestacion": "2018-09-10 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1013022451",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "759455",' +
                        '"efector_realizador": "GAMBA ARIEL ALEJANDRO",' +
                        '"prescriptor": null,' +
                        '"efector_prescriptor": null,' +
                        '"presentado": "336.7",' +
                        '"importe": "336.7",' +
                        '"presentacion": "218110765",' +
                        '"nro_factura": "6490",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7901",' +
                        '"lote": "815002",' +
                        '"renglones": "38024044",' +
                        '"pca_id": "73773189",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "7",' +
                        '"fecha_prestacion": "2018-10-01 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "04000208",' +
                        '"desc_prestacion": "OBTURACION CON LAMPARA DE LUZ HALOGENA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": "45",' +
                        '"caras": "O",' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "737673",' +
                        '"efector_realizador": "ECHAZU EUGENIA",' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "385.84",' +
                        '"importe": "385.84",' +
                        '"presentacion": "219010724",' +
                        '"nro_factura": "1681",' +
                        '"lugar_realizacion": "ASOC. ODONTOLOGICA DE ROSARIO",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": "812345",' +
                        '"renglones": "37856063",' +
                        '"pca_id": "73494546",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "8",' +
                        '"fecha_prestacion": "2018-10-01 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "04000208",' +
                        '"desc_prestacion": "OBTURACION CON LAMPARA DE LUZ HALOGENA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": "37",' +
                        '"caras": "O",' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "737673",' +
                        '"efector_realizador": "ECHAZU EUGENIA",' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "385.84",' +
                        '"importe": "385.84",' +
                        '"presentacion": "219010724",' +
                        '"nro_factura": "1681",' +
                        '"lugar_realizacion": "ASOC. ODONTOLOGICA DE ROSARIO",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": "812345",' +
                        '"renglones": "37856062",' +
                        '"pca_id": "73494545",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "9",' +
                        '"fecha_prestacion": "2019-01-08 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Autorizacion",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": null,' +
                        '"nombre_diagnostico": null,' +
                        '"cantidad": "1",' +
                        '"prestacion": "18741",' +
                        '"desc_prestacion": "BACTRIM FORTE, COMP.X 10",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": "1013826453",' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "706571",' +
                        '"efector_realizador": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"prescriptor": "942035",' +
                        '"efector_prescriptor": "MARTINEZ MARIA JIMENA",' +
                        '"presentado": "0",' +
                        '"importe": "0",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "73091778",' +
                        '"origen": "On-Line"' +
                    '},' +
                    '{' +
                        '"rn": "10",' +
                        '"fecha_prestacion": "2018-12-31 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Autorizacion",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": null,' +
                        '"nombre_diagnostico": null,' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": "1013784902",' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "0",' +
                        '"importe": "0",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "INST. GAMMA",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "72947270",' +
                        '"origen": "On-Line"' +
                    '},' +
                    '{' +
                        '"rn": "11",' +
                        '"fecha_prestacion": "2018-12-29 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Autorizacion",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": null,' +
                        '"nombre_diagnostico": null,' +
                        '"cantidad": "1",' +
                        '"prestacion": "18741",' +
                        '"desc_prestacion": "BACTRIM FORTE, COMP.X 10",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": "1013782016",' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "706571",' +
                        '"efector_realizador": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"prescriptor": "553322",' +
                        '"efector_prescriptor": "MANZO TATIANA GISELE",' +
                        '"presentado": "0",' +
                        '"importe": "0",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "72942156",' +
                        '"origen": "On-Line"' +
                    '},' +
                    '{' +
                        '"rn": "12",' +
                        '"fecha_prestacion": "2018-12-29 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Autorizacion",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": null,' +
                        '"nombre_diagnostico": null,' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": "1013781872",' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "0",' +
                        '"importe": "0",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "INST. GAMMA",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "72941822",' +
                        '"origen": "On-Line"' +
                    '},' +
                    '{' +
                        '"rn": "13",' +
                        '"fecha_prestacion": "2018-09-06 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": "11",' +
                        '"autorizacion": "1013004330",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "756279",' +
                        '"efector_realizador": "ARDUSSO LEDIT RAMON FRANCISCO",' +
                        '"prescriptor": "756279",' +
                        '"efector_prescriptor": "ARDUSSO LEDIT RAMON FRANCISCO",' +
                        '"presentado": "311.91",' +
                        '"importe": "311.91",' +
                        '"presentacion": "218100818",' +
                        '"nro_factura": "1249",' +
                        '"lugar_realizacion": "INST. ESPECIALIDADES DE LA SALUD ROSARIO",' +
                        '"nro_caja_archivo": "7754",' +
                        '"lote": "797981",' +
                        '"renglones": "37062868",' +
                        '"pca_id": "72284691",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "14",' +
                        '"fecha_prestacion": "2018-08-31 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "42203",' +
                        '"desc_prestacion": "ALENYS, INHAL.NASAL DS.X 120",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "0",' +
                        '"importe": "104.15",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "71799015",' +
                        '"origen": "Post"' +
                    '},' +
                    '{' +
                        '"rn": "15",' +
                        '"fecha_prestacion": "2018-08-29 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "11939",' +
                        '"desc_prestacion": "ERNEX, COMP.DESLEIBLES X 10",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "0",' +
                        '"importe": "37.23",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "71797690",' +
                        '"origen": "Post"' +
                    '},' +
                    '{' +
                        '"rn": "16",' +
                        '"fecha_prestacion": "2018-08-29 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "48356",' +
                        '"desc_prestacion": "TOFLUX, 600 MG SOB.X 10",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "0",' +
                        '"importe": "73.49",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "71797689",' +
                        '"origen": "Post"' +
                    '},' +
                    '{' +
                        '"rn": "17",' +
                        '"fecha_prestacion": "2018-07-01 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "04000203",' +
                        '"desc_prestacion": "OBTURACION CON AMALGAMA CAVIDAD COMPLEJA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": "33",' +
                        '"caras": "MDP",' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "810605",' +
                        '"efector_realizador": "ALMADA OSVALDO SERGIO",' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "643.72",' +
                        '"importe": "643.72",' +
                        '"presentacion": "218080758",' +
                        '"nro_factura": "1515",' +
                        '"lugar_realizacion": "ASOC. ODONTOLOGICA DE ROSARIO",' +
                        '"nro_caja_archivo": "7720",' +
                        '"lote": "780179",' +
                        '"renglones": "36032637",' +
                        '"pca_id": "70686099",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "18",' +
                        '"fecha_prestacion": "2018-07-01 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "04000203",' +
                        '"desc_prestacion": "OBTURACION CON AMALGAMA CAVIDAD COMPLEJA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": "34",' +
                        '"caras": "OMD",' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "810605",' +
                        '"efector_realizador": "ALMADA OSVALDO SERGIO",' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "643.72",' +
                        '"importe": "643.72",' +
                        '"presentacion": "218080758",' +
                        '"nro_factura": "1515",' +
                        '"lugar_realizacion": "ASOC. ODONTOLOGICA DE ROSARIO",' +
                        '"nro_caja_archivo": "7720",' +
                        '"lote": "780179",' +
                        '"renglones": "36032636",' +
                        '"pca_id": "70686098",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "19",' +
                        '"fecha_prestacion": "2018-07-01 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "04000203",' +
                        '"desc_prestacion": "OBTURACION CON AMALGAMA CAVIDAD COMPLEJA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": "35",' +
                        '"caras": "OMD",' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "810605",' +
                        '"efector_realizador": "ALMADA OSVALDO SERGIO",' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "643.72",' +
                        '"importe": "643.72",' +
                        '"presentacion": "218080758",' +
                        '"nro_factura": "1515",' +
                        '"lugar_realizacion": "ASOC. ODONTOLOGICA DE ROSARIO",' +
                        '"nro_caja_archivo": "7720",' +
                        '"lote": "780179",' +
                        '"renglones": "36032635",' +
                        '"pca_id": "70686097",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "20",' +
                        '"fecha_prestacion": "2018-07-01 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "04000203",' +
                        '"desc_prestacion": "OBTURACION CON AMALGAMA CAVIDAD COMPLEJA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": "38",' +
                        '"caras": "OMD",' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "810605",' +
                        '"efector_realizador": "ALMADA OSVALDO SERGIO",' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "643.72",' +
                        '"importe": "643.72",' +
                        '"presentacion": "218080758",' +
                        '"nro_factura": "1515",' +
                        '"lugar_realizacion": "ASOC. ODONTOLOGICA DE ROSARIO",' +
                        '"nro_caja_archivo": "7720",' +
                        '"lote": "780179",' +
                        '"renglones": "36032634",' +
                        '"pca_id": "70686096",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "21",' +
                        '"fecha_prestacion": "2018-10-05 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Autorizacion",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": "1013218126",' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "760416",' +
                        '"efector_realizador": "PEDEMONTE JOSE GERMAN",' +
                        '"prescriptor": "760416",' +
                        '"efector_prescriptor": "PEDEMONTE JOSE GERMAN",' +
                        '"presentado": "0",' +
                        '"importe": "0",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "70537941",' +
                        '"origen": "On-Line"' +
                    '},' +
                    '{' +
                        '"rn": "22",' +
                        '"fecha_prestacion": "2018-10-05 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Autorizacion",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": "1013218104",' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "874621",' +
                        '"efector_realizador": "DEMARIA JUAN PABLO",' +
                        '"prescriptor": "874621",' +
                        '"efector_prescriptor": "DEMARIA JUAN PABLO",' +
                        '"presentado": "0",' +
                        '"importe": "0",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "70537920",' +
                        '"origen": "On-Line"' +
                    '},' +
                    '{' +
                        '"rn": "23",' +
                        '"fecha_prestacion": "2018-06-19 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "R10",' +
                        '"nombre_diagnostico": "DOLOR ABDOMINAL Y PÉLVICO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02430109",' +
                        '"desc_prestacion": "SALA DE RECUPERACION",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1012414045",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "759455",' +
                        '"efector_realizador": "GAMBA ARIEL ALEJANDRO",' +
                        '"prescriptor": "759455",' +
                        '"efector_prescriptor": "GAMBA ARIEL ALEJANDRO",' +
                        '"presentado": "947.6",' +
                        '"importe": "947.6",' +
                        '"presentacion": "218080667",' +
                        '"nro_factura": "5836",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7592",' +
                        '"lote": "782987",' +
                        '"renglones": "36246979",' +
                        '"pca_id": "70530613",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "24",' +
                        '"fecha_prestacion": "2018-06-19 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "R10",' +
                        '"nombre_diagnostico": "DOLOR ABDOMINAL Y PÉLVICO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02500201",' +
                        '"desc_prestacion": "MEDICAMENTOS EXENTOS",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1012414045",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": "759455",' +
                        '"efector_realizador": "GAMBA ARIEL ALEJANDRO",' +
                        '"prescriptor": "759455",' +
                        '"efector_prescriptor": "GAMBA ARIEL ALEJANDRO",' +
                        '"presentado": "416.41",' +
                        '"importe": "416.41",' +
                        '"presentacion": "218080667",' +
                        '"nro_factura": "5836",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7592",' +
                        '"lote": "782987",' +
                        '"renglones": "36246975",' +
                        '"pca_id": "70530612",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "25",' +
                        '"fecha_prestacion": "2018-06-19 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "R10",' +
                        '"nombre_diagnostico": "DOLOR ABDOMINAL Y PÉLVICO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02205013",' +
                        '"desc_prestacion": "VIDEO-ESOFAGOGASTRODUODENOSCOPIA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1012414045",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "759455",' +
                        '"efector_realizador": "GAMBA ARIEL ALEJANDRO",' +
                        '"prescriptor": "759455",' +
                        '"efector_prescriptor": "GAMBA ARIEL ALEJANDRO",' +
                        '"presentado": "2462.03",' +
                        '"importe": "2462.03",' +
                        '"presentacion": "218080667",' +
                        '"nro_factura": "5836",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7592",' +
                        '"lote": "782987",' +
                        '"renglones": "36246974",' +
                        '"pca_id": "70530611",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "26",' +
                        '"fecha_prestacion": "2018-06-19 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "R10",' +
                        '"nombre_diagnostico": "DOLOR ABDOMINAL Y PÉLVICO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02205014",' +
                        '"desc_prestacion": "VIDEO-COLONOSCOPIA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1012414045",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "759455",' +
                        '"efector_realizador": "GAMBA ARIEL ALEJANDRO",' +
                        '"prescriptor": "759455",' +
                        '"efector_prescriptor": "GAMBA ARIEL ALEJANDRO",' +
                        '"presentado": "3168.36",' +
                        '"importe": "3168.36",' +
                        '"presentacion": "218080667",' +
                        '"nro_factura": "5836",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7592",' +
                        '"lote": "782987",' +
                        '"renglones": "36246973",' +
                        '"pca_id": "70530610",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "27",' +
                        '"fecha_prestacion": "2018-06-19 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "2",' +
                        '"prestacion": "02150101",' +
                        '"desc_prestacion": "BIOPSIA POR INCISION O POR PUNCION. GANCLIO,LESION DE PIEL, TROZO DE OVARIO,CILINDRO HIG.",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1012442009",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "502972",' +
                        '"efector_realizador": "CUELLO FATIMA GUILLERMINA",' +
                        '"prescriptor": "759455",' +
                        '"efector_prescriptor": "GAMBA ARIEL ALEJANDRO",' +
                        '"presentado": "1414",' +
                        '"importe": "1413.16",' +
                        '"presentacion": "218080667",' +
                        '"nro_factura": "5832",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7592",' +
                        '"lote": "782990",' +
                        '"renglones": "36247319",' +
                        '"pca_id": "70525544",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "28",' +
                        '"fecha_prestacion": "2018-07-04 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1012541090",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "759455",' +
                        '"efector_realizador": "GAMBA ARIEL ALEJANDRO",' +
                        '"prescriptor": null,' +
                        '"efector_prescriptor": null,' +
                        '"presentado": "314.67",' +
                        '"importe": "314.67",' +
                        '"presentacion": "218080667",' +
                        '"nro_factura": "5832",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7592",' +
                        '"lote": "782990",' +
                        '"renglones": "36247170",' +
                        '"pca_id": "70525174",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "29",' +
                        '"fecha_prestacion": "2018-06-14 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02166001",' +
                        '"desc_prestacion": "ANESTESIA COMPLEJIDAD I",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": "70",' +
                        '"autorizacion": "1012414045",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "884713",' +
                        '"efector_realizador": "SCHLEIFER DANIEL BENJAMIN",' +
                        '"prescriptor": "759455",' +
                        '"efector_prescriptor": "GAMBA ARIEL ALEJANDRO",' +
                        '"presentado": "1389.75",' +
                        '"importe": "1389.75",' +
                        '"presentacion": "218080382",' +
                        '"nro_factura": "21387",' +
                        '"lugar_realizacion": "ASOC. ROSARINA DE ANESTESIA, ANALGESIA Y REANIMACION",' +
                        '"nro_caja_archivo": "7550",' +
                        '"lote": "784559",' +
                        '"renglones": "36342698",' +
                        '"pca_id": "70208503",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "30",' +
                        '"fecha_prestacion": "2018-06-14 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02166002",' +
                        '"desc_prestacion": "ANESTESIA COMPLEJIDAD II",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": "70",' +
                        '"autorizacion": "1012414045",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "884713",' +
                        '"efector_realizador": "SCHLEIFER DANIEL BENJAMIN",' +
                        '"prescriptor": "759455",' +
                        '"efector_prescriptor": "GAMBA ARIEL ALEJANDRO",' +
                        '"presentado": "2570",' +
                        '"importe": "2570",' +
                        '"presentacion": "218080382",' +
                        '"nro_factura": "21387",' +
                        '"lugar_realizacion": "ASOC. ROSARINA DE ANESTESIA, ANALGESIA Y REANIMACION",' +
                        '"nro_caja_archivo": "7550",' +
                        '"lote": "784559",' +
                        '"renglones": "36342697",' +
                        '"pca_id": "70208502",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "31",' +
                        '"fecha_prestacion": "2018-06-01 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "04000203",' +
                        '"desc_prestacion": "OBTURACION CON AMALGAMA CAVIDAD COMPLEJA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": "24",' +
                        '"caras": "OMD",' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "810605",' +
                        '"efector_realizador": "ALMADA OSVALDO SERGIO",' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "643.72",' +
                        '"importe": "643.72",' +
                        '"presentacion": "218070815",' +
                        '"nro_factura": "1465",' +
                        '"lugar_realizacion": "ASOC. ODONTOLOGICA DE ROSARIO",' +
                        '"nro_caja_archivo": "7573",' +
                        '"lote": "770621",' +
                        '"renglones": "35458147",' +
                        '"pca_id": "69930063",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "32",' +
                        '"fecha_prestacion": "2018-06-01 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "04000203",' +
                        '"desc_prestacion": "OBTURACION CON AMALGAMA CAVIDAD COMPLEJA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": "25",' +
                        '"caras": "OMD",' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "810605",' +
                        '"efector_realizador": "ALMADA OSVALDO SERGIO",' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "643.72",' +
                        '"importe": "643.72",' +
                        '"presentacion": "218070815",' +
                        '"nro_factura": "1465",' +
                        '"lugar_realizacion": "ASOC. ODONTOLOGICA DE ROSARIO",' +
                        '"nro_caja_archivo": "7573",' +
                        '"lote": "770621",' +
                        '"renglones": "35458146",' +
                        '"pca_id": "69930062",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "33",' +
                        '"fecha_prestacion": "2018-06-01 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "04000203",' +
                        '"desc_prestacion": "OBTURACION CON AMALGAMA CAVIDAD COMPLEJA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": "28",' +
                        '"caras": "OMD",' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "810605",' +
                        '"efector_realizador": "ALMADA OSVALDO SERGIO",' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "643.72",' +
                        '"importe": "643.72",' +
                        '"presentacion": "218070815",' +
                        '"nro_factura": "1465",' +
                        '"lugar_realizacion": "ASOC. ODONTOLOGICA DE ROSARIO",' +
                        '"nro_caja_archivo": "7573",' +
                        '"lote": "770621",' +
                        '"renglones": "35458145",' +
                        '"pca_id": "69930061",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "34",' +
                        '"fecha_prestacion": "2018-06-01 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "04000101",' +
                        '"desc_prestacion": "CONSULTA, DIAGNOSTICO, FICHADO Y PLAN DE TRATAMIENTO",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "810605",' +
                        '"efector_realizador": "ALMADA OSVALDO SERGIO",' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "255.56",' +
                        '"importe": "255.56",' +
                        '"presentacion": "218070815",' +
                        '"nro_factura": "1465",' +
                        '"lugar_realizacion": "ASOC. ODONTOLOGICA DE ROSARIO",' +
                        '"nro_caja_archivo": "7573",' +
                        '"lote": "770621",' +
                        '"renglones": "35458144",' +
                        '"pca_id": "69930060",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "35",' +
                        '"fecha_prestacion": "2018-06-13 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1012406062",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "759455",' +
                        '"efector_realizador": "GAMBA ARIEL ALEJANDRO",' +
                        '"prescriptor": null,' +
                        '"efector_prescriptor": null,' +
                        '"presentado": "294.08",' +
                        '"importe": "294.08",' +
                        '"presentacion": "218070474",' +
                        '"nro_factura": "5694",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7516",' +
                        '"lote": "776633",' +
                        '"renglones": "35863028",' +
                        '"pca_id": "69868052",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "36",' +
                        '"fecha_prestacion": "2018-06-14 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": "11",' +
                        '"autorizacion": "1012410977",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "754009",' +
                        '"efector_realizador": "CAVALIERI ENRIQUE JOSE",' +
                        '"prescriptor": "754009",' +
                        '"efector_prescriptor": "CAVALIERI ENRIQUE JOSE",' +
                        '"presentado": "237.2",' +
                        '"importe": "237.2",' +
                        '"presentacion": "218070342",' +
                        '"nro_factura": "1635",' +
                        '"lugar_realizacion": "INST. DE CARDIOLOGIA DE ROSARIO",' +
                        '"nro_caja_archivo": "7502",' +
                        '"lote": "772131",' +
                        '"renglones": "35593507",' +
                        '"pca_id": "69603472",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "37",' +
                        '"fecha_prestacion": "2018-06-14 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02170101",' +
                        '"desc_prestacion": "ELECTROCARDIOGRAMA EN CONSULTORIO-CON O SIN PRUEBA          DE ESFUERZO)",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": "11",' +
                        '"autorizacion": "1012410966",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "754009",' +
                        '"efector_realizador": "CAVALIERI ENRIQUE JOSE",' +
                        '"prescriptor": "754009",' +
                        '"efector_prescriptor": "CAVALIERI ENRIQUE JOSE",' +
                        '"presentado": "120.23",' +
                        '"importe": "120.23",' +
                        '"presentacion": "218070342",' +
                        '"nro_factura": "1635",' +
                        '"lugar_realizacion": "INST. DE CARDIOLOGIA DE ROSARIO",' +
                        '"nro_caja_archivo": "7502",' +
                        '"lote": "772131",' +
                        '"renglones": "35593506",' +
                        '"pca_id": "69603471",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "38",' +
                        '"fecha_prestacion": "2018-06-07 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": "11",' +
                        '"autorizacion": "1012367904",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "756279",' +
                        '"efector_realizador": "ARDUSSO LEDIT RAMON FRANCISCO",' +
                        '"prescriptor": "756279",' +
                        '"efector_prescriptor": "ARDUSSO LEDIT RAMON FRANCISCO",' +
                        '"presentado": "291.5",' +
                        '"importe": "291.5",' +
                        '"presentacion": "218070404",' +
                        '"nro_factura": "1122",' +
                        '"lugar_realizacion": "INST. ESPECIALIDADES DE LA SALUD ROSARIO",' +
                        '"nro_caja_archivo": "7504",' +
                        '"lote": "771156",' +
                        '"renglones": "35496122",' +
                        '"pca_id": "69601643",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "39",' +
                        '"fecha_prestacion": "2018-06-18 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "44455",' +
                        '"desc_prestacion": "FOSFACOL 2F, FCO.X 2 X 45 ML",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "0",' +
                        '"importe": "88.75",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "69355490",' +
                        '"origen": "Post"' +
                    '},' +
                    '{' +
                        '"rn": "40",' +
                        '"fecha_prestacion": "2018-05-11 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "46132",' +
                        '"desc_prestacion": "EUMOTIL S, COMP.REC.X 30",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "0",' +
                        '"importe": "62.9",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "69307705",' +
                        '"origen": "Post"' +
                    '},' +
                    '{' +
                        '"rn": "41",' +
                        '"fecha_prestacion": "2018-02-05 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Medicamento",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "46985",' +
                        '"desc_prestacion": "TAURAL PLUS LIQUIDO, SUSP.X 200 ML",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1EA--AA",' +
                        '"nombre_estado": "AUTORIZADO POR EL AUDITOR",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "753976",' +
                        '"efector_prescriptor": "MEDICO A DESIGNAR",' +
                        '"presentado": "0",' +
                        '"importe": "50.31",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": "COMPAÑIA DE SERVICIOS FARMACEUTICOS",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "69203153",' +
                        '"origen": "Post"' +
                    '},' +
                    '{' +
                        '"rn": "42",' +
                        '"fecha_prestacion": "2018-05-02 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1012128946",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "759455",' +
                        '"efector_realizador": "GAMBA ARIEL ALEJANDRO",' +
                        '"prescriptor": null,' +
                        '"efector_prescriptor": null,' +
                        '"presentado": "294.08",' +
                        '"importe": "294.08",' +
                        '"presentacion": "218060393",' +
                        '"nro_factura": "5520",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7459",' +
                        '"lote": "770636",' +
                        '"renglones": "35460082",' +
                        '"pca_id": "69088007",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "43",' +
                        '"fecha_prestacion": "2018-03-27 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1011913399",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "883571",' +
                        '"efector_realizador": "AGUZZI ALEXIS ROMAN",' +
                        '"prescriptor": null,' +
                        '"efector_prescriptor": null,' +
                        '"presentado": "267.35",' +
                        '"importe": "267.35",' +
                        '"presentacion": "218050432",' +
                        '"nro_factura": "5321",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7358",' +
                        '"lote": "758930",' +
                        '"renglones": "34778884",' +
                        '"pca_id": "68113680",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "44",' +
                        '"fecha_prestacion": "2018-06-14 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Autorizacion",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "R10",' +
                        '"nombre_diagnostico": "DOLOR ABDOMINAL Y PÉLVICO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02160101",' +
                        '"desc_prestacion": "ANESTESIA MINIMA PARA PROCEDIMIENTOS DIAGNOSTICOS O TERAPEU-TICOS.(INCLUYE ANEST.GRAL Y..",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": "1012414045",' +
                        '"hd": null,' +
                        '"autorizacion": null,' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": null,' +
                        '"efector_realizador": null,' +
                        '"prescriptor": "759455",' +
                        '"efector_prescriptor": "GAMBA ARIEL ALEJANDRO",' +
                        '"presentado": "0",' +
                        '"importe": "0",' +
                        '"presentacion": null,' +
                        '"nro_factura": null,' +
                        '"lugar_realizacion": " ",' +
                        '"nro_caja_archivo": null,' +
                        '"lote": null,' +
                        '"renglones": null,' +
                        '"pca_id": "67207939",' +
                        '"origen": "Aut. Previa"' +
                    '},' +
                    '{' +
                        '"rn": "45",' +
                        '"fecha_prestacion": "2018-02-09 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "02420101",' +
                        '"desc_prestacion": "CONSULTA MEDICA",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1011635349",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "883571",' +
                        '"efector_realizador": "AGUZZI ALEXIS ROMAN",' +
                        '"prescriptor": null,' +
                        '"efector_prescriptor": null,' +
                        '"presentado": "259.56",' +
                        '"importe": "259.56",' +
                        '"presentacion": "218030266",' +
                        '"nro_factura": "4916",' +
                        '"lugar_realizacion": "SANATORIO AMERICANO",' +
                        '"nro_caja_archivo": "7207",' +
                        '"lote": "750973",' +
                        '"renglones": "34278749",' +
                        '"pca_id": "66576978",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "46",' +
                        '"fecha_prestacion": "2018-03-22 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "030938",' +
                        '"desc_prestacion": "VITAMINA B12",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1011883852",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "720376",' +
                        '"efector_realizador": "FAY OSCAR",' +
                        '"prescriptor": "883571",' +
                        '"efector_prescriptor": "AGUZZI ALEXIS ROMAN",' +
                        '"presentado": "469.35",' +
                        '"importe": "469.35",' +
                        '"presentacion": "218040369",' +
                        '"nro_factura": "720",' +
                        '"lugar_realizacion": "CIBIC",' +
                        '"nro_caja_archivo": "7204",' +
                        '"lote": "754040",' +
                        '"renglones": "34458544",' +
                        '"pca_id": "66537758",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "47",' +
                        '"fecha_prestacion": "2018-03-22 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "030887",' +
                        '"desc_prestacion": "TROMBOPLASTINA, TIEMPO DE (KPTT - TTPC - KT)",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1011883852",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "720376",' +
                        '"efector_realizador": "FAY OSCAR",' +
                        '"prescriptor": "883571",' +
                        '"efector_prescriptor": "AGUZZI ALEXIS ROMAN",' +
                        '"presentado": "62.58",' +
                        '"importe": "62.58",' +
                        '"presentacion": "218040369",' +
                        '"nro_factura": "720",' +
                        '"lugar_realizacion": "CIBIC",' +
                        '"nro_caja_archivo": "7204",' +
                        '"lote": "754040",' +
                        '"renglones": "34458543",' +
                        '"pca_id": "66537757",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "48",' +
                        '"fecha_prestacion": "2018-03-22 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "030837",' +
                        '"desc_prestacion": "SIDEROFILINA, CAPACIDAD DE SATURACION",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1011883852",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "720376",' +
                        '"efector_realizador": "FAY OSCAR",' +
                        '"prescriptor": "883571",' +
                        '"efector_prescriptor": "AGUZZI ALEXIS ROMAN",' +
                        '"presentado": "31.29",' +
                        '"importe": "31.29",' +
                        '"presentacion": "218040369",' +
                        '"nro_factura": "720",' +
                        '"lugar_realizacion": "CIBIC",' +
                        '"nro_caja_archivo": "7204",' +
                        '"lote": "754040",' +
                        '"renglones": "34458542",' +
                        '"pca_id": "66537756",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "49",' +
                        '"fecha_prestacion": "2018-03-22 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "030818",' +
                        '"desc_prestacion": "RETICULOCITOS RECUENTO de",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1011883852",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "720376",' +
                        '"efector_realizador": "FAY OSCAR",' +
                        '"prescriptor": "883571",' +
                        '"efector_prescriptor": "AGUZZI ALEXIS ROMAN",' +
                        '"presentado": "62.58",' +
                        '"importe": "62.58",' +
                        '"presentacion": "218040369",' +
                        '"nro_factura": "720",' +
                        '"lugar_realizacion": "CIBIC",' +
                        '"nro_caja_archivo": "7204",' +
                        '"lote": "754040",' +
                        '"renglones": "34458541",' +
                        '"pca_id": "66537755",' +
                        '"origen": null' +
                    '},' +
                    '{' +
                        '"rn": "50",' +
                        '"fecha_prestacion": "2018-03-22 00:00:00",' +
                        '"afi_afi_id": "458495",' +
                        '"tipo": "Consumo",' +
                        '"tipo_prestacion": "Nomenclador",' +
                        '"diagnostico": "999",' +
                        '"nombre_diagnostico": "DIAGNOSTICO INDETERMINADO",' +
                        '"cantidad": "1",' +
                        '"prestacion": "030771",' +
                        '"desc_prestacion": "PROTROMBINA, TIEMPO DE (TP)",' +
                        '"reintegro": null,' +
                        '"nro_autorizacion": null,' +
                        '"hd": null,' +
                        '"autorizacion": "1011883852",' +
                        '"pieza": null,' +
                        '"caras": null,' +
                        '"vda_drv_estado_auditoria": "C1----AS",' +
                        '"nombre_estado": "AUTORIZADO POR EL SISTEMA",' +
                        '"efector": "720376",' +
                        '"efector_realizador": "FAY OSCAR",' +
                        '"prescriptor": "883571",' +
                        '"efector_prescriptor": "AGUZZI ALEXIS ROMAN",' +
                        '"presentado": "62.58",' +
                        '"importe": "62.58",' +
                        '"presentacion": "218040369",' +
                        '"nro_factura": "720",' +
                        '"lugar_realizacion": "CIBIC",' +
                        '"nro_caja_archivo": "7204",' +
                        '"lote": "754040",' +
                        '"renglones": "34458540",' +
                        '"pca_id": "66537754",' +
                        '"origen": null' +
                    '}' +
                '],' +
                '"links": {' +
                    '"first": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/autorizaciones/consumos/191670-15?page=1",' +
                    '"last": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/autorizaciones/consumos/191670-15?page=3",' +
                    '"prev": null,' +
                    '"next": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/autorizaciones/consumos/191670-15?page=2"' +
                '},' +
                '"meta": {' +
                    '"current_page": 1,' +
                    '"from": 1,' +
                    '"last_page": 3,' +
                    '"path": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/autorizaciones/consumos/191670-15",' +
                    '"per_page": 50,' +
                    '"to": 50,' +
                    '"total": 110,' +
                    '"allowed_filters": [],' +
                    '"allowed_sorts": [],' +
                    '"allowed_appends": [],' +
                    '"allowed_fields": [],' +
                    '"allowed_includes": [],' +
                    '"default_includes": [],' +
                    '"optional_get_vars": {' +
                        '"sortBy": [],' +
                        '"sortOrder": [' +
                            '"asc",' +
                            '"desc"' +
                        '],' +
                        '"pageSize": {' +
                            '"0": "?pageSize=0",' +
                            '"15": "?pageSize=15",' +
                            '"50": "?pageSize=50",' +
                            '"100": "?pageSize=100"' +
                        '}' +
                    '}' +
                '}' +
            '}';
	}

	public static String getError(){
		return
			'{' +
				'"data": {' +
					'"error": true,' +
					'"errors": [],' +
					'"errorType": "exception",' +
					'"httpCode": 404,' +
					'"message": "Código de Afiliado inválido.",' +
					'"debug_message": [],' +
					'"exception": "NotFoundHttpException",' +
					'"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php",' +
					'"line": 964' +
				'}' +
			'}';
	}
}