public class WSAsociadoGetCuotasMock {
    public static String getFound(){
        return
            '{' +
                '"data": [' +
                    '{' +
                        '"valores_cuota_id": 8999908,' +
                        '"periodo": "2019-05-01",' +
                        '"fecha_generacion": "2019-04-23",' +
                        '"monto": "7051.94",' +
                        '"cuadro_costos": "E630001-M AS200-S1",' +
                        '"recargo_bonificacion": null,' +
                        '"monto_regla_adicional": "0",' +
                        '"monto_general": "0",' +
                        '"monto_bonificacion_recargo": "0",' +
                        '"liquidada": "F",' +
                        '"ajustada": "F",' +
                        '"detalle": [' +
                            '{' +
                                '"clausula": "CUOTA BASICA",' +
                                '"categoria_grupal": "INDIVIDUO",' +
                                '"regla_adicional": null,' +
                                '"cantidad": "0",' +
                                '"importe_final": "7051.94",' +
                                '"importe_regla_adicional": "0",' +
                                '"importe_cuadro_costo": "0",' +
                                '"importe_bonif_recargo": "0",' +
                                '"coeficiente": "1",' +
                                '"coeficiente_general": "1",' +
                                '"coeficiente_b_r": "1",' +
                                '"dca_id": "79512995",' +
                                '"dca_id_ajuste": null,' +
                                '"codigo_afiliado": null,' +
                                '"apellidos": null,' +
                                '"nombres": null' +
                            '}' +
                        ']' +
                    '},' +
                    '{' +
                        '"valores_cuota_id": 8892996,' +
                        '"periodo": "2019-04-01",' +
                        '"fecha_generacion": "2019-04-04",' +
                        '"monto": "6559.94",' +
                        '"cuadro_costos": "E630001-M AS200-S1",' +
                        '"recargo_bonificacion": null,' +
                        '"monto_regla_adicional": "0",' +
                        '"monto_general": "0",' +
                        '"monto_bonificacion_recargo": "0",' +
                        '"liquidada": "F",' +
                        '"ajustada": "F",' +
                        '"detalle": [' +
                            '{' +
                                '"clausula": "CUOTA BASICA",' +
                                '"categoria_grupal": "INDIVIDUO",' +
                                '"regla_adicional": null,' +
                                '"cantidad": "0",' +
                                '"importe_final": "6559.94",' +
                                '"importe_regla_adicional": "0",' +
                                '"importe_cuadro_costo": "0",' +
                                '"importe_bonif_recargo": "0",' +
                                '"coeficiente": "1",' +
                                '"coeficiente_general": "1",' +
                                '"coeficiente_b_r": "1",' +
                                '"dca_id": "79196149",' +
                                '"dca_id_ajuste": null,' +
                                '"codigo_afiliado": null,' +
                                '"apellidos": null,' +
                                '"nombres": null' +
                            '}' +
                        ']' +
                    '},' +
                    '{' +
                        '"valores_cuota_id": 8840913,' +
                        '"periodo": "2019-03-01",' +
                        '"fecha_generacion": "2019-02-22",' +
                        '"monto": "6559.94",' +
                        '"cuadro_costos": "E630001-M AS200-S1",' +
                        '"recargo_bonificacion": null,' +
                        '"monto_regla_adicional": "0",' +
                        '"monto_general": "0",' +
                        '"monto_bonificacion_recargo": "0",' +
                        '"liquidada": "F",' +
                        '"ajustada": "F",' +
                        '"detalle": [' +
                            '{' +
                                '"clausula": "CUOTA BASICA",' +
                                '"categoria_grupal": "INDIVIDUO",' +
                                '"regla_adicional": null,' +
                                '"cantidad": "0",' +
                                '"importe_final": "6559.94",' +
                                '"importe_regla_adicional": "0",' +
                                '"importe_cuadro_costo": "0",' +
                                '"importe_bonif_recargo": "0",' +
                                '"coeficiente": "1",' +
                                '"coeficiente_general": "1",' +
                                '"coeficiente_b_r": "1",' +
                                '"dca_id": "78793697",' +
                                '"dca_id_ajuste": null,' +
                                '"codigo_afiliado": null,' +
                                '"apellidos": null,' +
                                '"nombres": null' +
                            '}' +
                        ']' +
                    '},' +
                    '{' +
                        '"valores_cuota_id": 8784417,' +
                        '"periodo": "2019-02-01",' +
                        '"fecha_generacion": "2019-01-18",' +
                        '"monto": "6559.94",' +
                        '"cuadro_costos": "E630001-M AS200-S1",' +
                        '"recargo_bonificacion": null,' +
                        '"monto_regla_adicional": "0",' +
                        '"monto_general": "0",' +
                        '"monto_bonificacion_recargo": "0",' +
                        '"liquidada": "F",' +
                        '"ajustada": "F",' +
                        '"detalle": [' +
                            '{' +
                                '"clausula": "CUOTA BASICA",' +
                                '"categoria_grupal": "INDIVIDUO",' +
                                '"regla_adicional": null,' +
                                '"cantidad": "0",' +
                                '"importe_final": "6559.94",' +
                                '"importe_regla_adicional": "0",' +
                                '"importe_cuadro_costo": "0",' +
                                '"importe_bonif_recargo": "0",' +
                                '"coeficiente": "1",' +
                                '"coeficiente_general": "1",' +
                                '"coeficiente_b_r": "1",' +
                                '"dca_id": "78359528",' +
                                '"dca_id_ajuste": null,' +
                                '"codigo_afiliado": null,' +
                                '"apellidos": null,' +
                                '"nombres": null' +
                            '}' +
                        ']' +
                    '},' +
                    '{' +
                        '"valores_cuota_id": 8711083,' +
                        '"periodo": "2019-01-01",' +
                        '"fecha_generacion": "2018-12-18",' +
                        '"monto": "6247.56",' +
                        '"cuadro_costos": "E630001-M AS200-S1",' +
                        '"recargo_bonificacion": null,' +
                        '"monto_regla_adicional": "0",' +
                        '"monto_general": "0",' +
                        '"monto_bonificacion_recargo": "0",' +
                        '"liquidada": "F",' +
                        '"ajustada": "F",' +
                        '"detalle": [' +
                            '{' +
                                '"clausula": "CUOTA BASICA",' +
                                '"categoria_grupal": "INDIVIDUO",' +
                                '"regla_adicional": null,' +
                                '"cantidad": "0",' +
                                '"importe_final": "6247.56",' +
                                '"importe_regla_adicional": "0",' +
                                '"importe_cuadro_costo": "0",' +
                                '"importe_bonif_recargo": "0",' +
                                '"coeficiente": "1",' +
                                '"coeficiente_general": "1",' +
                                '"coeficiente_b_r": "1",' +
                                '"dca_id": "77829723",' +
                                '"dca_id_ajuste": null,' +
                                '"codigo_afiliado": null,' +
                                '"apellidos": null,' +
                                '"nombres": null' +
                            '}' +
                        ']' +
                    '},' +
                    '{' +
                        '"valores_cuota_id": 8618052,' +
                        '"periodo": "2018-12-01",' +
                        '"fecha_generacion": "2018-11-16",' +
                        '"monto": "6247.56",' +
                        '"cuadro_costos": "E630001-M AS200-S1",' +
                        '"recargo_bonificacion": null,' +
                        '"monto_regla_adicional": "0",' +
                        '"monto_general": "0",' +
                        '"monto_bonificacion_recargo": "0",' +
                        '"liquidada": "F",' +
                        '"ajustada": "F",' +
                        '"detalle": [' +
                            '{' +
                                '"clausula": "CUOTA BASICA",' +
                                '"categoria_grupal": "INDIVIDUO",' +
                                '"regla_adicional": null,' +
                                '"cantidad": "0",' +
                                '"importe_final": "6247.56",' +
                                '"importe_regla_adicional": "0",' +
                                '"importe_cuadro_costo": "0",' +
                                '"importe_bonif_recargo": "0",' +
                                '"coeficiente": "1",' +
                                '"coeficiente_general": "1",' +
                                '"coeficiente_b_r": "1",' +
                                '"dca_id": "77090528",' +
                                '"dca_id_ajuste": null,' +
                                '"codigo_afiliado": null,' +
                                '"apellidos": null,' +
                                '"nombres": null' +
                            '}' +
                        ']' +
                    '},' +
                    '{' +
                        '"valores_cuota_id": 8521103,' +
                        '"periodo": "2018-11-01",' +
                        '"fecha_generacion": "2018-10-18",' +
                        '"monto": "5758.12",' +
                        '"cuadro_costos": "E630001-M AS200-S1",' +
                        '"recargo_bonificacion": null,' +
                        '"monto_regla_adicional": "0",' +
                        '"monto_general": "0",' +
                        '"monto_bonificacion_recargo": "0",' +
                        '"liquidada": "F",' +
                        '"ajustada": "F",' +
                        '"detalle": [' +
                            '{' +
                                '"clausula": "CUOTA BASICA",' +
                                '"categoria_grupal": "INDIVIDUO",' +
                                '"regla_adicional": null,' +
                                '"cantidad": "0",' +
                                '"importe_final": "5758.12",' +
                                '"importe_regla_adicional": "0",' +
                                '"importe_cuadro_costo": "0",' +
                                '"importe_bonif_recargo": "0",' +
                                '"coeficiente": "1",' +
                                '"coeficiente_general": "1",' +
                                '"coeficiente_b_r": "1",' +
                                '"dca_id": "76445902",' +
                                '"dca_id_ajuste": null,' +
                                '"codigo_afiliado": null,' +
                                '"apellidos": null,' +
                                '"nombres": null' +
                            '}' +
                        ']' +
                    '}' +
                '],' +
                '"meta": {' +
                    '"allowed_filters": [],' +
                    '"allowed_sorts": [],' +
                    '"allowed_appends": [],' +
                    '"allowed_fields": [],' +
                    '"allowed_includes": [],' +
                    '"default_includes": [],' +
                    '"optional_get_vars": {' +
                        '"sortBy": [],' +
                        '"sortOrder": [' +
                            '"asc",' +
                            '"desc"' +
                        '],' +
                        '"pageSize": {' +
                            '"0": "?pageSize=0",' +
                            '"15": "?pageSize=15",' +
                            '"50": "?pageSize=50",' +
                            '"100": "?pageSize=100"' +
                        '}' +
                    '}' +
                '}' +
            '}';
            
    }
    
    public static String getError(){
		return
			'{' +
                '"data": {' +
                    '"error": true,' +
                    '"errors": [],' +
                    '"errorType": "exception",' +
                    '"httpCode": 404,' +
                    '"message": "El código o ID del Afiliado es inválido.",' +
                    '"debug_message": [],' +
                    '"exception": "NotFoundHttpException",' +
                    '"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php",' +
                    '"line": 964' +
                '}' +
            '}';
	}
}