public class WSAsociadoGetDomiciliosMock  {

	public static String getFound(){
		return
			'{' +
				'"data": [' +
					'{' +
						'"id_domicilio": "100162",' +
						'"tipo_domicilio": "COM",' +
						'"calle": "ZONA RURAL",' +
						'"piso": null,' +
						'"dpto": null,' +
						'"numero": null,' +
						'"codigo_postal": "2743ARY",' +
						'"localidad": "ARROYO DULCE",' +
						'"provincia": "BUENOS AIRES",' +
						'"pais": "ARGENTINA",' +
						'"telefonos": [' +
							'{' +
								'"tipo_telefono": "TEL",' +
								'"numero": "02395-454173"' +
							'}' +
						']' +
					'}' +
				'],' +
				'"meta": {' +
					'"allowed_filters": [],' +
					'"allowed_sorts": [],' +
					'"allowed_appends": [],' +
					'"allowed_fields": [],' +
					'"allowed_includes": [],' +
					'"default_includes": [],' +
					'"optional_get_vars": {' +
						'"sortBy": [],' +
						'"sortOrder": [' +
							'"asc",' +
							'"desc"' +
						'],' +
						'"pageSize": {' +
							'"0": "?pageSize=0",' +
							'"15": "?pageSize=15",' +
							'"50": "?pageSize=50",' +
							'"100": "?pageSize=100"' +
						'}' +
					'}' +
				'}' +
			'}';
	}

	public static String getFoundEmpresa(){
		return
			'{' +
				'"data": [' +
					'{' +
						'"domiemp_id": "5545",' +
						'"calle": "MORENO",' +
						'"numero": "467",' +
						'"piso": null,' +
						'"dpto": null,' +
						'"codigo_postal": "7500TAR",' +
						'"localidad": "TRES ARROYOS",' +
						'"provincia": "BUENOS AIRES",' +
						'"pais": "ARGENTINA",' +
						'"observaciones": null,' +
						'"tipo_domicilio": "COM",' +
						'"telefonos": [' +
							'{' +
								'"telemp_id": 5106,' +
								'"tipo": "TEL",' +
								'"numero": "02983-430755"' +
							'}' +
						']' +
					'}' +
				'],' +
				'"meta": {' +
					'"allowed_filters": [],' +
					'"allowed_sorts": [],' +
					'"allowed_appends": [],' +
					'"allowed_fields": [],' +
					'"allowed_includes": [],' +
					'"default_includes": [],' +
					'"optional_get_vars": {' +
						'"sortBy": [],' +
						'"sortOrder": [' +
							'"asc",' +
							'"desc"' +
						'],' +
						'"pageSize": {' +
							'"0": "?pageSize=0",' +
							'"15": "?pageSize=15",' +
							'"50": "?pageSize=50",' +
							'"100": "?pageSize=100"' +
						'}' +
					'}' +
				'}' +
			'}';
	}

	public static String getFoundObraSocial(){
		return
			'{' +
				'"data": [' +
					'{' +
						'"id": "89",' +
						'"calle": "ANCHORENA",' +
						'"numero": "639",' +
						'"piso": null,' +
						'"dpto": null,' +
						'"codigo_postal": "1170CFE",' +
						'"localidad": "CAPITAL FEDERAL",' +
						'"provincia": "CAPITAL FEDERAL",' +
						'"pais": "ARGENTINA",' +
						'"observaciones": null,' +
						'"tipo_domicilio": "COM",' +
						'"telefonos": [' +
							'{' +
								'"id": "49",' +
								'"tipo": "TEL",' +
								'"numero": "011-41064500"' +
							'}' +
						']' +
					'},' +
					'{' +
						'"id": "89",' +
						'"calle": "ANCHORENA",' +
						'"numero": "639",' +
						'"piso": null,' +
						'"dpto": null,' +
						'"codigo_postal": "1170CFE",' +
						'"localidad": "CAPITAL FEDERAL",' +
						'"provincia": "CAPITAL FEDERAL",' +
						'"pais": "ARGENTINA",' +
						'"observaciones": null,' +
						'"tipo_domicilio": "LEG",' +
						'"telefonos": [' +
							'{' +
								'"id": "49",' +
								'"tipo": "TEL",' +
								'"numero": "011-41064500"' +
							'}' +
						']' +
					'}' +
				'],' +
				'"meta": {' +
					'"allowed_filters": [],' +
					'"allowed_sorts": [],' +
					'"allowed_appends": [],' +
					'"allowed_fields": [],' +
					'"allowed_includes": [],' +
					'"default_includes": [],' +
					'"optional_get_vars": {' +
						'"sortBy": [],' +
						'"sortOrder": [' +
							'"asc",' +
							'"desc"' +
						'],' +
						'"pageSize": {' +
							'"0": "?pageSize=0",' +
							'"15": "?pageSize=15",' +
							'"50": "?pageSize=50",' +
							'"100": "?pageSize=100"' +
						'}' +
					'}' +
				'}' +
			'}';
	}

	public static String getFoundEfector(){
		return
            '{' +
                '"data": [' +
                    '{' +
                        '"efector": "536787",' +
                        '"nombre_efector": "MONACO ABALOS JAVIER LUIS",' +
                        '"domicilio_efector": "SAN LORENZO 882 D   ",' +
                        '"codigo_postal": "2000ROS",' +
                        '"localidad": "ROSARIO",' +
                        '"codigo_povincia": "S",' +
                        '"provincia": "SANTA FE",' +
                        '"tipo_domicilio": "COM",' +
                        '"desc_domicilio": "COMERCIAL",' +
                        '"domiefe_id": "156102"' +
                    '}' +
                '],' +
                '"meta": {' +
                    '"allowed_filters": [],' +
                    '"allowed_sorts": [],' +
                    '"allowed_appends": [],' +
                    '"allowed_fields": [],' +
                    '"allowed_includes": [],' +
                    '"default_includes": [],' +
                    '"optional_get_vars": {' +
                        '"sortBy": [],' +
                        '"sortOrder": [' +
                            '"asc",' +
                            '"desc"' +
                        '],' +
                        '"pageSize": {' +
                            '"0": "?pageSize=0",' +
                            '"15": "?pageSize=15",' +
                            '"50": "?pageSize=50",' +
                            '"100": "?pageSize=100"' +
                        '}' +
                    '}' +
                '}' +
            '}';
			
	}

	public static String getFoundDelegaciones(){
		return
            '{' +
                '"data": [' +
                    '{' +
                        '"tipo_delegacion": "AGENCIA",' +
                        '"codigo": "650030",' +
                        '"nombre": "650030_AG.NORTE PROV.BS.AS.-MUTUAL ASOCIADOS COOP.OBRERA",' +
                        '"descripcion": "MUTUAL ASOCIADOS COOP.OBRERA",' +
                        '"fecha_activacion": "2018-08-01 00:00:00",' +
                        '"estado": "A",' +
                        '"organizacion": "BUE",' +
                        '"correo_electronico": "MSALAZAR@COOPERATIVAOBRERA.COOP",' +
                        '"observaciones": null,' +
                        '"domicilio": "DONADO 320  ",' +
                        '"localidad": "BAHIA BLANCA",' +
                        '"provincia": "BUENOS AIRES",' +
                        '"url_convenio": null,' +
                        '"filial_depende": "650916",' +
                        '"pje_comis_dateras": "50",' +
                        '"nivel_permiso": "D",' +
                        '"correo_gerencia_coop": null,' +
                        '"tipo_comision_venta": "INCENTIVADA_D",' +
                        '"telefonos": [' +
                            '{' +
                                '"teldel_id": 1037,' +
                                '"tipo": "TEL",' +
                                '"numero": "0",' +
                                '"del_os_osoc_codigo": "640100",' +
                                '"del_os_codigo": "650030"' +
                            '}' +
                        ']' +
                    '}' +
                '],' +
                '"meta": {' +
                    '"allowed_filters": [' +
                        '"codigo",' +
                        '"nombre",' +
                        '"organizacion",' +
                        '"filial_depende "' +
                    '],' +
                    '"allowed_sorts": [],' +
                    '"allowed_appends": [],' +
                    '"allowed_fields": [],' +
                    '"allowed_includes": [],' +
                    '"default_includes": [],' +
                    '"optional_get_vars": {' +
                        '"sortBy": [],' +
                        '"sortOrder": [' +
                            '"asc",' +
                            '"desc"' +
                        '],' +
                        '"pageSize": {' +
                            '"0": "?pageSize=0",' +
                            '"15": "?pageSize=15",' +
                            '"50": "?pageSize=50",' +
                            '"100": "?pageSize=100"' +
                        '}' +
                    '}' +
                '}' +
            '}';
	}


	public static String getError() {
		return
			'{' +
				'"data": {' +
					'"error": true,' +
					'"errors": [],' +
					'"errorType": "exception",' +
					'"httpCode": 404,' +
					'"message": "La ruta que está buscando no existe.",' +
					'"debug_message": [],' +
					'"exception": "NotFoundHttpException",' +
					'"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteCollection.php",' +
					'"line": 179' +
				'}' +
			'}';
	}
}