public class WSAsociadoGetHistoricoMock  {

	public static String getFound(){
		return
            '{' +
                '"data": [' +
                    '{' +
                        '"replicado": "V",' +
                        '"fecha_vigencia": "2017-07-01",' +
                        '"cambia_codigo": "F",' +
                        '"codigo": "191670/15",' +
                        '"cambia_estado": "F",' +
                        '"estado": "A",' +
                        '"cambia_afiliacion": "F",' +
                        '"afiliacion": "Obligatorio",' +
                        '"cambia_aporta": "F",' +
                        '"aporta": "Verdadero",' +
                        '"cambia_tipo_afiliado": "F",' +
                        '"tipo_afiliado": "Titular",' +
                        '"codigo_titular": null,' +
                        '"apellidos_titular": null,' +
                        '"nombres_titular": null,' +
                        '"cambia_parentesco": "F",' +
                        '"parentesco_codigo": null,' +
                        '"parentesco_descripcion": null,' +
                        '"cambia_empresa": "V",' +
                        '"empresa_codigo": "600011",' +
                        '"sucursal_codigo": "1",' +
                        '"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
                        '"sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
                        '"cambia_plan": "V",' +
                        '"plan_codigo": "AS300",' +
                        '"plan_nombre": "SUPERIOR AS300",' +
                        '"cambia_obra_social": "F",' +
                        '"obra_social_codigo": "640005",' +
                        '"obra_social_nombre": "OSDEPYM",' +
                        '"cambia_estado_civil": "F",' +
                        '"estado_civil": "Soltero",' +
                        '"cambia_discapacitado": "F",' +
                        '"discapacitado": "Falso",' +
                        '"cambia_fecha_alta_adm": "F",' +
                        '"fecha_alta_adm": "2016-05-01",' +
                        '"cambia_antiguedad": "F",' +
                        '"antiguedad_reconocida": "0",' +
                        '"cambia_adherente": "F",' +
                        '"adherente": "F",' +
                        '"cambia_agencia": "F",' +
                        '"delegacion_os": "640100",' +
                        '"agencia_codigo": "650098",' +
                        '"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
                        '"cambia_agrupacion": "V",' +
                        '"agrupacion": "OBLEMP",' +
                        '"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
                        '"cambia_agrupacion1": "V",' +
                        '"agrupacion1": "MEN",' +
                        '"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
                        '"cambia_agrupacion2": "V",' +
                        '"agrupacion2": "OTROS",' +
                        '"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
                        '"cambia_agrupacion3": "V",' +
                        '"agrupacion3": "SC",' +
                        '"agrupacion3_nombre": "SIN CARENCIAS",' +
                        '"cambia_agrupacion4": "F",' +
                        '"agrupacion4": null,' +
                        '"agrupacion4_nombre": null,' +
                        '"tipo_baja_codigo": null,' +
                        '"tipo_baja_nombre": null,' +
                        '"motivo_baja": null,' +
                        '"cambia_categoria": "V",' +
                        '"categoria_codigo": "GEN",' +
                        '"categoria_nombre": "GENERICO",' +
                        '"cambio_a_nivel_de": "Propio",' +
                        '"hist_afi_id": "957068",' +
                        '"afi_id_titular": "458495",' +
                        '"novedades": [' +
                            '{' +
                                '"fecha": "2017-05-31",' +
                                '"usuario": null,' +
                                '"solicitud": null,' +
                                '"fecha_vigencia": null,' +
                                '"tipo_solicitud": null,' +
                                '"tipo_baja": null,' +
                                '"motivo": null,' +
                                '"masiva": "V",' +
                                '"rotulo": null,' +
                                '"solicitud_masiva": "150",' +
                                '"afi_id": "458495",' +
                                '"hist_afi_id": "957068"' +
                            '},' +
                            '{' +
                                '"fecha": "2017-05-31",' +
                                '"usuario": null,' +
                                '"solicitud": null,' +
                                '"fecha_vigencia": null,' +
                                '"tipo_solicitud": null,' +
                                '"tipo_baja": null,' +
                                '"motivo": null,' +
                                '"masiva": "V",' +
                                '"rotulo": null,' +
                                '"solicitud_masiva": "151",' +
                                '"afi_id": "458495",' +
                                '"hist_afi_id": "957068"' +
                            '},' +
                            '{' +
                                '"fecha": "2017-05-31",' +
                                '"usuario": null,' +
                                '"solicitud": null,' +
                                '"fecha_vigencia": null,' +
                                '"tipo_solicitud": null,' +
                                '"tipo_baja": null,' +
                                '"motivo": null,' +
                                '"masiva": "V",' +
                                '"rotulo": null,' +
                                '"solicitud_masiva": "152",' +
                                '"afi_id": "458495",' +
                                '"hist_afi_id": "957068"' +
                            '},' +
                            '{' +
                                '"fecha": "2017-05-31",' +
                                '"usuario": null,' +
                                '"solicitud": null,' +
                                '"fecha_vigencia": null,' +
                                '"tipo_solicitud": null,' +
                                '"tipo_baja": null,' +
                                '"motivo": null,' +
                                '"masiva": "V",' +
                                '"rotulo": null,' +
                                '"solicitud_masiva": "153",' +
                                '"afi_id": "458495",' +
                                '"hist_afi_id": "957068"' +
                            '},' +
                            '{' +
                                '"fecha": "2017-06-05",' +
                                '"usuario": "JGERLO",' +
                                '"solicitud": "586168",' +
                                '"fecha_vigencia": "2017-07-01",' +
                                '"tipo_solicitud": "MODIF_PLAN_E_IF",' +
                                '"tipo_baja": null,' +
                                '"motivo": null,' +
                                '"masiva": "F",' +
                                '"rotulo": null,' +
                                '"solicitud_masiva": null,' +
                                '"afi_id": "458495",' +
                                '"hist_afi_id": "957068"' +
                            '}' +
                        ']' +
                    '},' +
                    '{' +
                        '"replicado": "V",' +
                        '"fecha_vigencia": "2016-08-01",' +
                        '"cambia_codigo": "F",' +
                        '"codigo": "191670/15",' +
                        '"cambia_estado": "F",' +
                        '"estado": "A",' +
                        '"cambia_afiliacion": "V",' +
                        '"afiliacion": "Obligatorio",' +
                        '"cambia_aporta": "F",' +
                        '"aporta": "Verdadero",' +
                        '"cambia_tipo_afiliado": "F",' +
                        '"tipo_afiliado": "Titular",' +
                        '"codigo_titular": null,' +
                        '"apellidos_titular": null,' +
                        '"nombres_titular": null,' +
                        '"cambia_parentesco": "F",' +
                        '"parentesco_codigo": null,' +
                        '"parentesco_descripcion": null,' +
                        '"cambia_empresa": "V",' +
                        '"empresa_codigo": "600011",' +
                        '"sucursal_codigo": "1",' +
                        '"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
                        '"sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
                        '"cambia_plan": "V",' +
                        '"plan_codigo": "7",' +
                        '"plan_nombre": "PLAN 7",' +
                        '"cambia_obra_social": "V",' +
                        '"obra_social_codigo": "640005",' +
                        '"obra_social_nombre": "OSDEPYM",' +
                        '"cambia_estado_civil": "V",' +
                        '"estado_civil": "Soltero",' +
                        '"cambia_discapacitado": "V",' +
                        '"discapacitado": "Falso",' +
                        '"cambia_fecha_alta_adm": "F",' +
                        '"fecha_alta_adm": "2016-05-01",' +
                        '"cambia_antiguedad": "V",' +
                        '"antiguedad_reconocida": "0",' +
                        '"cambia_adherente": "F",' +
                        '"adherente": "F",' +
                        '"cambia_agencia": "F",' +
                        '"delegacion_os": "640100",' +
                        '"agencia_codigo": "650098",' +
                        '"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
                        '"cambia_agrupacion": "V",' +
                        '"agrupacion": "OBLEMP",' +
                        '"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
                        '"cambia_agrupacion1": "V",' +
                        '"agrupacion1": "MEN",' +
                        '"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
                        '"cambia_agrupacion2": "V",' +
                        '"agrupacion2": "OTROS",' +
                        '"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
                        '"cambia_agrupacion3": "V",' +
                        '"agrupacion3": "SC",' +
                        '"agrupacion3_nombre": "SIN CARENCIAS",' +
                        '"cambia_agrupacion4": "F",' +
                        '"agrupacion4": null,' +
                        '"agrupacion4_nombre": null,' +
                        '"tipo_baja_codigo": null,' +
                        '"tipo_baja_nombre": null,' +
                        '"motivo_baja": null,' +
                        '"cambia_categoria": "V",' +
                        '"categoria_codigo": "GEN",' +
                        '"categoria_nombre": "GENERICO",' +
                        '"cambio_a_nivel_de": "Propio",' +
                        '"hist_afi_id": "870044",' +
                        '"afi_id_titular": "458495",' +
                        '"novedades": [' +
                            '{' +
                                '"fecha": "2016-08-09",' +
                                '"usuario": "NFERNANDEZ",' +
                                '"solicitud": "530432",' +
                                '"fecha_vigencia": "2016-08-01",' +
                                '"tipo_solicitud": "MODIF_TIT",' +
                                '"tipo_baja": null,' +
                                '"motivo": null,' +
                                '"masiva": "F",' +
                                '"rotulo": null,' +
                                '"solicitud_masiva": null,' +
                                '"afi_id": "458495",' +
                                '"hist_afi_id": "870044"' +
                            '},' +
                            '{' +
                                '"fecha": "2016-08-09",' +
                                '"usuario": "NFERNANDEZ",' +
                                '"solicitud": "530432",' +
                                '"fecha_vigencia": "2016-08-01",' +
                                '"tipo_solicitud": "MODIF_TIT",' +
                                '"tipo_baja": null,' +
                                '"motivo": null,' +
                                '"masiva": "F",' +
                                '"rotulo": null,' +
                                '"solicitud_masiva": null,' +
                                '"afi_id": "458495",' +
                                '"hist_afi_id": "870044"' +
                            '}' +
                        ']' +
                    '},' +
                    '{' +
                        '"replicado": "V",' +
                        '"fecha_vigencia": "2016-05-01",' +
                        '"cambia_codigo": "V",' +
                        '"codigo": "191670/15",' +
                        '"cambia_estado": "V",' +
                        '"estado": "A",' +
                        '"cambia_afiliacion": "V",' +
                        '"afiliacion": "Voluntario",' +
                        '"cambia_aporta": "V",' +
                        '"aporta": "Falso",' +
                        '"cambia_tipo_afiliado": "V",' +
                        '"tipo_afiliado": "Titular",' +
                        '"codigo_titular": null,' +
                        '"apellidos_titular": null,' +
                        '"nombres_titular": null,' +
                        '"cambia_parentesco": "V",' +
                        '"parentesco_codigo": null,' +
                        '"parentesco_descripcion": null,' +
                        '"cambia_empresa": "V",' +
                        '"empresa_codigo": "600011",' +
                        '"sucursal_codigo": "7",' +
                        '"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
                        '"sucursal_nombre": "EMPLEADOS ACA SALUD RECIEN INGRESADOS",' +
                        '"cambia_plan": "V",' +
                        '"plan_codigo": "7",' +
                        '"plan_nombre": "PLAN 7",' +
                        '"cambia_obra_social": "V",' +
                        '"obra_social_codigo": "640100",' +
                        '"obra_social_nombre": "ACA SALUD",' +
                        '"cambia_estado_civil": "V",' +
                        '"estado_civil": "Soltero",' +
                        '"cambia_discapacitado": "V",' +
                        '"discapacitado": "Falso",' +
                        '"cambia_fecha_alta_adm": "V",' +
                        '"fecha_alta_adm": "2016-05-01",' +
                        '"cambia_antiguedad": "V",' +
                        '"antiguedad_reconocida": "0",' +
                        '"cambia_adherente": "V",' +
                        '"adherente": "F",' +
                        '"cambia_agencia": "V",' +
                        '"delegacion_os": "640100",' +
                        '"agencia_codigo": "650098",' +
                        '"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
                        '"cambia_agrupacion": "V",' +
                        '"agrupacion": "VOLEMP",' +
                        '"agrupacion_nombre": "AFILIADOS VOLUNTARIOS POR EMPRESA",' +
                        '"cambia_agrupacion1": "V",' +
                        '"agrupacion1": "MEN",' +
                        '"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
                        '"cambia_agrupacion2": "V",' +
                        '"agrupacion2": "OTROS",' +
                        '"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
                        '"cambia_agrupacion3": "V",' +
                        '"agrupacion3": "SC",' +
                        '"agrupacion3_nombre": "SIN CARENCIAS",' +
                        '"cambia_agrupacion4": "V",' +
                        '"agrupacion4": null,' +
                        '"agrupacion4_nombre": null,' +
                        '"tipo_baja_codigo": null,' +
                        '"tipo_baja_nombre": null,' +
                        '"motivo_baja": null,' +
                        '"cambia_categoria": "V",' +
                        '"categoria_codigo": "GEN",' +
                        '"categoria_nombre": "GENERICO",' +
                        '"cambio_a_nivel_de": "Propio",' +
                        '"hist_afi_id": "851193",' +
                        '"afi_id_titular": "458495",' +
                        '"novedades": [' +
                            '{' +
                                '"fecha": "2016-05-20",' +
                                '"usuario": "JREAL",' +
                                '"solicitud": "516055",' +
                                '"fecha_vigencia": "2016-05-01",' +
                                '"tipo_solicitud": "ALTA",' +
                                '"tipo_baja": null,' +
                                '"motivo": null,' +
                                '"masiva": "F",' +
                                '"rotulo": null,' +
                                '"solicitud_masiva": null,' +
                                '"afi_id": "458495",' +
                                '"hist_afi_id": "851193"' +
                            '}' +
                        ']' +
                    '}' +
                '],' +
                '"meta": {' +
                    '"allowed_filters": [],' +
                    '"allowed_sorts": [],' +
                    '"allowed_appends": [],' +
                    '"allowed_fields": [],' +
                    '"allowed_includes": [],' +
                    '"default_includes": [],' +
                    '"optional_get_vars": {' +
                        '"sortBy": [],' +
                        '"sortOrder": [' +
                            '"asc",' +
                            '"desc"' +
                        '],' +
                        '"pageSize": {' +
                            '"0": "?pageSize=0",' +
                            '"15": "?pageSize=15",' +
                            '"50": "?pageSize=50",' +
                            '"100": "?pageSize=100"' +
                        '}' +
                    '}' +
                '}' +
            '}';
	}

	public static String getError(){
		return
			'{' +
				'"data": {' +
					'"error": true,' +
					'"errors": [],' +
					'"errorType": "exception",' +
					'"httpCode": 404,' +
					'"message": "Código de Afiliado inválido.",' +
					'"debug_message": [],' +
					'"exception": "NotFoundHttpException",' +
					'"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php",' +
					'"line": 964' +
				'}' +
			'}';
	}
}