public class WSAsociadoGetAsociadoMock  {
	
	public static String getFound(){
		return
			'{' +
			  '"data": [' +
				'{' +
				  '"afi_id": 134495,' +
				  '"afi_id_tit": null,' +
				  '"entidad": "60667",' +
				  '"codigo": "60667/18",' +
				  '"apellidos": "OGANDO",' +
				  '"nombres": "VANINA NATALIA",' +
				  '"discapacitado": "F",' +
				  '"tipo_afiliado": "Titular",' +
				  '"parentesco": null,' +
				  '"tiene_alertas": "V",' +
				  '"estado": "Activo",' +
				  '"plan_codigo": "AS200",' +
				  '"plan_nombre": "INTEGRAL AS200",' +
				  '"modelo_plan_codigo": "AS200",' +
				  '"modelo_plan_nombre": "INTEGRAL AS200",' +
				  '"agencia_codigo": "650008",' +
				  '"agencia_nombre": "650008_AG.BAHIA BLANCA-MUTUAL ASOCIADOS COOP.OBRERA",' +
				  '"categoria_codigo": "GEN",' +
				  '"categoria_nombre": "GENERICO",' +
				  '"agrupacion_codigo": "VOLDIR",' +
				  '"agrupacion_nombre": "AFILIADOS VOLUNTARIOS DIRECTOS",' +
				  '"agrupacion1_codigo": "MEN",' +
				  '"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
				  '"agrupacion2_codigo": "DEBAUT",' +
				  '"agrupacion2_nombre": "PAGOS POR DEBITO AUTOMATICO",' +
				  '"agrupacion3_codigo": "SC",' +
				  '"agrupacion3_nombre": "SIN CARENCIAS",' +
				  '"agrupacion4_codigo": null,' +
				  '"agrupacion4_nombre": null,' +
				  '"empresa_codigo": "639426",' +
				  '"empresa_sucursal": "9",' +
				  '"empresa_nombre": "MUTUAL ASOCIADOS COOPERATIVA OBRERA",' +
				  '"empresa_sucursal_nombre": "REING 2 DA SEM AS200/204 VOLDIR CBU/TC PC 2017",' +
				  '"afiliacion": "Sin Aportes",' +
				  '"aporta": "Falso",' +
				  '"obra_social_codigo": "640100",' +
				  '"obra_social_nombre": "ACA SALUD",' +
				  '"obra_social_ant_codigo": "640003",' +
				  '"obra_social_ant_nombre": "SPM",' +
				  '"tipo_documento": "DNI",' +
				  '"numero_documento": "23130343",' +
				  '"sexo": "Femenino",' +
				  '"fecha_nacimiento": "1973-02-06",' +
				  '"edad": "46",' +
				  '"estado_civil": "Soltero",' +
				  '"codigo_1": "054",' +
				  '"gentilicio": "ARGENTINO",' +
				  '"actividad_codigo": "COM",' +
				  '"actividad_nombre": "COMERCIANTE",' +
				  '"titular_codigo": null,' +
				  '"titular_apellidos": null,' +
				  '"titular_nombres": null,' +
				  '"antiguedad_reconocida": "-223",' +
				  '"ultima_alta": "2018-12-01",' +
				  '"fecha_alta_administrativa": "2000-05-01",' +
				  '"fecha_alta": "2002-10-02",' +
				  '"fecha_vigencia": "2019-01-01",' +
				  '"cuit": "27231303435",' +
				  '"sujeto_facturacion": "Verdadero",' +
				  '"adherente": "Falso",' +
				  '"tipo_baja_codigo": null,' +
				  '"tipo_baja_nombre": null,' +
				  '"motivo_de_baja": null,' +
				  '"excedente": null,' +
				  '"entidad_codigo": "60667",' +
				  '"full_name": "OGANDO VANINA NATALIA"' +
				'}' +
			  ']' +
			'}';
	}
}