@isTest
public class WSBatchAsociadoMock  {
	public static String getFound(){
		return
			'{' +
				'"data": [' +
					'{' +
						'"rn": "1",' +
						'"afi_id": 140975,' +
						'"afi_id_tit": null,' +
						'"entidad": "69791",' +
						'"codigo": "69791/17",' +
						'"apellidos": "ESPINOSA GABRIEL ERNESTO",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "20173680",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1968-03-12",' +
						'"edad": "51",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "EMPL",' +
						'"actividad_nombre": "EMPLEADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2017-07-01",' +
						'"cuit": "20201736804",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69791",' +
						'"mail": "vmartinez@bbe-sa.com.ar",' +
						'"provincia": "A",' +
						'"localidad": "1200",' +
						'"tipo_telefono": "TEL",' +
						'"fecha_baja": "2019-10-01 00:00:00",' +
						'"pais_codigo": "AR",' +
						'"full_name": "ESPINOSA GABRIEL ERNESTO"' +
					'},' +
					'{' +
						'"rn": "2",' +
						'"afi_id": 140976,' +
						'"afi_id_tit": null,' +
						'"entidad": "69792",' +
						'"codigo": "69792/16",' +
						'"apellidos": "SAVORETTI GABRIEL GERMAN",' +
						'"nombres": ".",' +
						'"pam": "V",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "22725723",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1972-07-06",' +
						'"edad": "47",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "EMPL",' +
						'"actividad_nombre": "EMPLEADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2017-07-01",' +
						'"cuit": "20227257238",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69792",' +
						'"full_name": "SAVORETTI GABRIEL GERMAN"' +
					'},' +
					'{' +
						'"rn": "3",' +
						'"afi_id": 140977,' +
						'"afi_id_tit": null,' +
						'"entidad": "69793",' +
						'"codigo": "69793/15",' +
						'"apellidos": "CRUCIANI SILVIA ELENA",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "14666853",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1961-03-15",' +
						'"edad": "58",' +
						'"estado_civil": "P",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "EMPL",' +
						'"actividad_nombre": "EMPLEADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2017-07-01",' +
						'"cuit": "23146668534",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69793",' +
						'"full_name": "CRUCIANI SILVIA ELENA"' +
					'},' +
					'{' +
						'"rn": "4",' +
						'"afi_id": 140979,' +
						'"afi_id_tit": null,' +
						'"entidad": "69795",' +
						'"codigo": "69795/13",' +
						'"apellidos": "YACOPINO ANDRES",' +
						'"nombres": ".",' +
						'"pam": "V",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "B",' +
						'"plan_codigo": "7",' +
						'"plan_nombre": "PLAN 7",' +
						'"modelo_plan_codigo": "7",' +
						'"modelo_plan_nombre": "MODELO DE PLAN 7",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "OSDEPYM",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "25328248",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1976-08-11",' +
						'"edad": "43",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "EMPL",' +
						'"actividad_nombre": "EMPLEADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2011-06-01",' +
						'"cuit": "20253282488",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": "NOSUBS",' +
						'"tipo_baja_nombre": "BAJA NO SUBVENCIONADA",' +
						'"motivo_de_baja": "BAJA POR DESVINCULACIÓN LABORAL",' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69795",' +
						'"full_name": "YACOPINO ANDRES"' +
					'},' +
					'{' +
						'"rn": "5",' +
						'"afi_id": 140980,' +
						'"afi_id_tit": null,' +
						'"entidad": "69796",' +
						'"codigo": "69796/12",' +
						'"apellidos": "CHYT, DIEGO EUGENIO",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "B",' +
						'"plan_codigo": "11/2",' +
						'"plan_nombre": "PLAN 11/2",' +
						'"modelo_plan_codigo": "11",' +
						'"modelo_plan_nombre": "MODELO DE PLAN 11",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "VOLDIR",' +
						'"agrupacion_nombre": "AFILIADOS VOLUNTARIOS DIRECTOS",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "AUTONOMOS GRUPO AFINIDAD AFIP ROSARIO",' +
						'"empresa_sucursal_nombre": "AFIP- VOLUNTARIOS",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "21415014",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1969-12-22",' +
						'"edad": "50",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "EMPL",' +
						'"actividad_nombre": "EMPLEADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2003-05-01",' +
						'"cuit": "20214150140",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": "NOSUBS",' +
						'"tipo_baja_nombre": "BAJA NO SUBVENCIONADA",' +
						'"motivo_de_baja": "BAJA",' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69796",' +
						'"full_name": "CHYT, DIEGO EUGENIO"' +
					'},' +
					'{' +
						'"rn": "6",' +
						'"afi_id": 140981,' +
						'"afi_id_tit": null,' +
						'"entidad": "69797",' +
						'"codigo": "69797/11",' +
						'"apellidos": "DRIUSSI MARCELA L.",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "14859616",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1962-01-16",' +
						'"edad": "57",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "EMPL",' +
						'"actividad_nombre": "EMPLEADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2017-07-01",' +
						'"cuit": "27148596161",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69797",' +
						'"full_name": "DRIUSSI MARCELA L."' +
					'},' +
					'{' +
						'"rn": "7",' +
						'"afi_id": 140982,' +
						'"afi_id_tit": null,' +
						'"entidad": "69798",' +
						'"codigo": "69798/10",' +
						'"apellidos": "ZUIANI",' +
						'"nombres": "ADRIANA ELISA",' +
						'"pam": "F",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "VOLDIR",' +
						'"agrupacion_nombre": "AFILIADOS VOLUNTARIOS DIRECTOS",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "DEBAUT",' +
						'"agrupacion2_nombre": "PAGOS POR DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "20",' +
						'"empresa_nombre": "AUTONOMOS ZONAS TRADICIONALES CASA BS AS",' +
						'"empresa_sucursal_nombre": "MIGRACION PLANES AS.",' +
						'"afiliacion": "Sin Aportes",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "ACA SALUD",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "11125617",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1953-06-21",' +
						'"edad": "66",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "JUBI",' +
						'"actividad_nombre": "JUBILADO / PENSIONADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2018-06-01",' +
						'"cuit": "27111256174",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69798",' +
						'"full_name": "ZUIANI ADRIANA ELISA"' +
					'},' +
					'{' +
						'"rn": "8",' +
						'"afi_id": 140983,' +
						'"afi_id_tit": null,' +
						'"entidad": "69799",' +
						'"codigo": "69799/19",' +
						'"apellidos": "LEDESMA ",' +
						'"nombres": "ARIELITO",' +
						'"pam": "F",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650071_ACA SALUD CASA CENTRAL",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "17390947",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1965-12-07",' +
						'"edad": "54",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "EMPL",' +
						'"actividad_nombre": "EMPLEADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2019-05-01",' +
						'"cuit": "20173909471",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69799",' +
						'"full_name": "LEDESMA  ARIELITO"' +
					'},' +
					'{' +
						'"rn": "9",' +
						'"afi_id": 180007,' +
						'"afi_id_tit": "140973",' +
						'"entidad": "69790",' +
						'"codigo": "69790/25",' +
						'"apellidos": "GOMEZ",' +
						'"nombres": "AGUSTIN",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "B",' +
						'"plan_codigo": "11 PMO",' +
						'"plan_nombre": "PLAN 11 PMO",' +
						'"modelo_plan_codigo": "PMO",' +
						'"modelo_plan_nombre": "MODELO PLAN PMO",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLDIR",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS DIRECTOS",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "2",' +
						'"empresa_nombre": "SOLO COBERTURA PMO CTROS.CONTRATADOS-EX AFIL. OBLIG.-",' +
						'"empresa_sucursal_nombre": "SOLO COBERTURA PMO CTROS.CONTRATADOS-DISTRACTO LABORAL-",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "34393225",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1989-02-19",' +
						'"edad": "30",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "27502/93",' +
						'"titular_apellidos": "LUGARINI GRACIELA N.",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2014-03-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": "NOSUBS",' +
						'"tipo_baja_nombre": "BAJA NO SUBVENCIONADA",' +
						'"motivo_de_baja": "BAJA POR DESVINCULACIÓN LABORAL",' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69790",' +
						'"es_menor": "F",' +
						'"full_name": "GOMEZ AGUSTIN"' +
					'},' +
					'{' +
						'"rn": "10",' +
						'"afi_id": 180009,' +
						'"afi_id_tit": "140975",' +
						'"entidad": "69791",' +
						'"codigo": "69791/24",' +
						'"apellidos": "RAMIREZ SUSANA MARGARITA",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "CO",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "20176560",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1968-02-10",' +
						'"edad": "51",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69791/17",' +
						'"titular_apellidos": "ESPINOSA GABRIEL ERNESTO",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2011-01-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69791",' +
						'"es_menor": "V",' +
						'"full_name": "RAMIREZ SUSANA MARGARITA"' +
					'},' +
					'{' +
						'"rn": "11",' +
						'"afi_id": 180010,' +
						'"afi_id_tit": "140975",' +
						'"entidad": "69791",' +
						'"codigo": "69791/31",' +
						'"apellidos": "ESPINOSA SOFIA BELEN",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "40905257",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1998-01-23",' +
						'"edad": "21",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69791/17",' +
						'"titular_apellidos": "ESPINOSA GABRIEL ERNESTO",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2011-01-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69791",' +
						'"full_name": "ESPINOSA SOFIA BELEN"' +
					'},' +
					'{' +
						'"rn": "12",' +
						'"afi_id": 180011,' +
						'"afi_id_tit": "140975",' +
						'"entidad": "69791",' +
						'"codigo": "69791/48",' +
						'"apellidos": "ESPINOSA MICAELA ORIANA",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "44021841",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "2002-02-22",' +
						'"edad": "17",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69791/17",' +
						'"titular_apellidos": "ESPINOSA GABRIEL ERNESTO",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2011-01-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69791",' +
						'"full_name": "ESPINOSA MICAELA ORIANA"' +
					'},' +
					'{' +
						'"rn": "13",' +
						'"afi_id": 180012,' +
						'"afi_id_tit": "140977",' +
						'"entidad": "69793",' +
						'"codigo": "69793/39",' +
						'"apellidos": "ALZUGARAY LUCIA",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "36004894",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1991-08-29",' +
						'"edad": "28",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69793/15",' +
						'"titular_apellidos": "CRUCIANI SILVIA ELENA",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2011-01-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69793",' +
						'"full_name": "ALZUGARAY LUCIA"' +
					'},' +
					'{' +
						'"rn": "14",' +
						'"afi_id": 180013,' +
						'"afi_id_tit": "140977",' +
						'"entidad": "69793",' +
						'"codigo": "69793/46",' +
						'"apellidos": "ALZUGARAY CAMILA",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "38135944",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1994-06-07",' +
						'"edad": "25",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69793/15",' +
						'"titular_apellidos": "CRUCIANI SILVIA ELENA",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2011-01-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69793",' +
						'"full_name": "ALZUGARAY CAMILA"' +
					'},' +
					'{' +
						'"rn": "15",' +
						'"afi_id": 180017,' +
						'"afi_id_tit": "140980",' +
						'"entidad": "69796",' +
						'"codigo": "69796/29",' +
						'"apellidos": "CATENA, DANIELA VERONICA",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "CO",' +
						'"tiene_alertas": "F",' +
						'"estado": "B",' +
						'"plan_codigo": "11/2",' +
						'"plan_nombre": "PLAN 11/2",' +
						'"modelo_plan_codigo": "11",' +
						'"modelo_plan_nombre": "MODELO DE PLAN 11",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "VOLDIR",' +
						'"agrupacion_nombre": "AFILIADOS VOLUNTARIOS DIRECTOS",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "609999",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "AUTONOMOS GRUPO AFINIDAD AFIP ROSARIO",' +
						'"empresa_sucursal_nombre": "AFIP- VOLUNTARIOS",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "24720181",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1975-08-21",' +
						'"edad": "44",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69796/12",' +
						'"titular_apellidos": "CHYT, DIEGO EUGENIO",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2003-05-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": "NOSUBS",' +
						'"tipo_baja_nombre": "BAJA NO SUBVENCIONADA",' +
						'"motivo_de_baja": "BAJA",' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69796",' +
						'"full_name": "CATENA, DANIELA VERONICA"' +
					'}' +
				'],' +
				'"links": {' +
					'"first": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019?page=1",' +
					'"last": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019?page=2",' +
					'"prev": null,' +
					'"next": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019?page=2"' +
				'},' +
				'"meta": {' +
					'"current_page": 1,' +
					'"from": 1,' +
					'"last_page": 2,' +
					'"path": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019",' +
					'"per_page": 15,' +
					'"to": 15,' +
					'"total": 25,' +
					'"allowed_filters": [],' +
					'"allowed_sorts": [],' +
					'"allowed_appends": [],' +
					'"allowed_fields": [],' +
					'"allowed_includes": [],' +
					'"default_includes": [],' +
					'"optional_get_vars": {' +
						'"sortBy": [],' +
						'"sortOrder": [' +
							'"asc",' +
							'"desc"' +
						'],' +
						'"pageSize": {' +
							'"0": "?pageSize=0",' +
							'"15": "?pageSize=15",' +
							'"50": "?pageSize=50",' +
							'"100": "?pageSize=100"' +
						'}' +
					'}' +
				'}' +
			'}';
	}
	public static String getFoundSecondPage(){
		return
			'{' +
				'"data": [' +
					'{' +
						'"rn": "16",' +
						'"afi_id": 180018,' +
						'"afi_id_tit": "140980",' +
						'"entidad": "69796",' +
						'"codigo": "69796/36",' +
						'"apellidos": "CHYT, MATIAS NICOLAS",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "B",' +
						'"plan_codigo": "11/2",' +
						'"plan_nombre": "PLAN 11/2",' +
						'"modelo_plan_codigo": "11",' +
						'"modelo_plan_nombre": "MODELO DE PLAN 11",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "VOLDIR",' +
						'"agrupacion_nombre": "AFILIADOS VOLUNTARIOS DIRECTOS",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "AUTONOMOS GRUPO AFINIDAD AFIP ROSARIO",' +
						'"empresa_sucursal_nombre": "AFIP- VOLUNTARIOS",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "43713260",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "2001-10-04",' +
						'"edad": "18",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69796/12",' +
						'"titular_apellidos": "CHYT, DIEGO EUGENIO",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2003-05-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": "NOSUBS",' +
						'"tipo_baja_nombre": "BAJA NO SUBVENCIONADA",' +
						'"motivo_de_baja": "BAJA",' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69796",' +
						'"permanencia_desde": "2020-07-01 00:00:00",' +
						'"permanencia_hasta": "2020-09-01 00:00:00",' +
						'"adhiere_fe": "N",' +
						'"full_name": "CHYT, MATIAS NICOLAS"' +
					'},' +
					'{' +
						'"rn": "17",' +
						'"afi_id": 180019,' +
						'"afi_id_tit": "140981",' +
						'"entidad": "69797",' +
						'"codigo": "69797/28",' +
						'"apellidos": "FERNANDEZ OMAR A.",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "CO",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "10779439",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1953-06-08",' +
						'"edad": "66",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69797/11",' +
						'"titular_apellidos": "DRIUSSI MARCELA L.",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2017-04-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69797",' +
						'"adhiere_fe": "S",' +
						'"full_name": "FERNANDEZ OMAR A."' +
					'},' +
					'{' +
						'"rn": "18",' +
						'"afi_id": 180022,' +
						'"afi_id_tit": "140981",' +
						'"entidad": "69797",' +
						'"codigo": "69797/42",' +
						'"apellidos": "FERNANDEZ AILIN",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "33734894",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1988-06-17",' +
						'"edad": "31",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69797/11",' +
						'"titular_apellidos": "DRIUSSI MARCELA L.",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2017-04-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69797",' +
						'"full_name": "FERNANDEZ AILIN"' +
					'},' +
					'{' +
						'"rn": "19",' +
						'"afi_id": 180023,' +
						'"afi_id_tit": "140983",' +
						'"entidad": "69799",' +
						'"codigo": "69799/26",' +
						'"apellidos": "MACIEL",' +
						'"nombres": "NIDIA BETTY",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "CO",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650071_ACA SALUD CASA CENTRAL",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "22421855",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1971-10-21",' +
						'"edad": "48",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69799/19",' +
						'"titular_apellidos": "LEDESMA ",' +
						'"titular_nombres": "ARIELITO",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2011-01-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69799",' +
						'"full_name": "MACIEL NIDIA BETTY"' +
					'},' +
					'{' +
						'"rn": "20",' +
						'"afi_id": 180024,' +
						'"afi_id_tit": "140983",' +
						'"entidad": "69799",' +
						'"codigo": "69799/33",' +
						'"apellidos": "LEDESMA ",' +
						'"nombres": "RAMIRO",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650071_ACA SALUD CASA CENTRAL",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "42270525",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1999-12-09",' +
						'"edad": "20",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69799/19",' +
						'"titular_apellidos": "LEDESMA ",' +
						'"titular_nombres": "ARIELITO",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2015-07-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69799",' +
						'"full_name": "LEDESMA  RAMIRO"' +
					'},' +
					'{' +
						'"rn": "21",' +
						'"afi_id": 185539,' +
						'"afi_id_tit": "140980",' +
						'"entidad": "69796",' +
						'"codigo": "69796/43",' +
						'"apellidos": "CHYT",' +
						'"nombres": "LUCILA BELEN",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "B",' +
						'"plan_codigo": "11/2",' +
						'"plan_nombre": "PLAN 11/2",' +
						'"modelo_plan_codigo": "11",' +
						'"modelo_plan_nombre": "MODELO DE PLAN 11",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "VOLDIR",' +
						'"agrupacion_nombre": "AFILIADOS VOLUNTARIOS DIRECTOS",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "AUTONOMOS GRUPO AFINIDAD AFIP ROSARIO",' +
						'"empresa_sucursal_nombre": "AFIP- VOLUNTARIOS",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "44630747",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "2003-03-02",' +
						'"edad": "16",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69796/12",' +
						'"titular_apellidos": "CHYT, DIEGO EUGENIO",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2003-03-01",' +
						'"fecha_alta_administrativa": "2003-03-01",' +
						'"fecha_alta": "2003-03-07",' +
						'"fecha_vigencia": "2003-05-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": "NOSUBS",' +
						'"tipo_baja_nombre": "BAJA NO SUBVENCIONADA",' +
						'"motivo_de_baja": "BAJA",' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69796",' +
						'"full_name": "CHYT LUCILA BELEN"' +
					'},' +
					'{' +
						'"rn": "22",' +
						'"afi_id": 185765,' +
						'"afi_id_tit": "140977",' +
						'"entidad": "69793",' +
						'"codigo": "69793/22",' +
						'"apellidos": "DA SILVA ALVES",' +
						'"nombres": "VALENTINA",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "43956796",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "2003-03-17",' +
						'"edad": "16",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69793/15",' +
						'"titular_apellidos": "CRUCIANI SILVIA ELENA",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2003-03-01",' +
						'"fecha_alta_administrativa": "2003-03-01",' +
						'"fecha_alta": "2003-03-21",' +
						'"fecha_vigencia": "2011-01-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69793",' +
						'"full_name": "DA SILVA ALVES VALENTINA"' +
					'},' +
					'{' +
						'"rn": "23",' +
						'"afi_id": 284759,' +
						'"afi_id_tit": "140977",' +
						'"entidad": "69793",' +
						'"codigo": "69793/53",' +
						'"apellidos": "DA SILVA ALVES",' +
						'"nombres": "MANUEL LUIS",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "CO",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "20529191",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1968-08-25",' +
						'"edad": "51",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69793/15",' +
						'"titular_apellidos": "CRUCIANI SILVIA ELENA",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2005-11-01",' +
						'"fecha_alta_administrativa": "2005-11-01",' +
						'"fecha_alta": "2005-11-01",' +
						'"fecha_vigencia": "2011-01-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69793",' +
						'"full_name": "DA SILVA ALVES MANUEL LUIS"' +
					'},' +
					'{' +
						'"rn": "24",' +
						'"afi_id": 306476,' +
						'"afi_id_tit": "140975",' +
						'"entidad": "69791",' +
						'"codigo": "69791/55",' +
						'"apellidos": "ESPINOSA",' +
						'"nombres": "MATIAS DAVID",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "48972144",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "2008-10-11",' +
						'"edad": "11",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69791/17",' +
						'"titular_apellidos": "ESPINOSA GABRIEL ERNESTO",' +
						'"titular_nombres": ".",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2008-10-01",' +
						'"fecha_alta_administrativa": "2008-10-01",' +
						'"fecha_alta": "2008-10-28",' +
						'"fecha_vigencia": "2011-01-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69791",' +
						'"full_name": "ESPINOSA MATIAS DAVID"' +
					'},' +
					'{' +
						'"rn": "25",' +
						'"afi_id": 305577,' +
						'"afi_id_tit": "140983",' +
						'"entidad": "69799",' +
						'"codigo": "69799/40",' +
						'"apellidos": "LEDESMA",' +
						'"nombres": "MORENA",' +
						'"pam": "F",' +
						'"tipo_afiliado": "FAM",' +
						'"parentesco": "HI",' +
						'"tiene_alertas": "F",' +
						'"estado": "A",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650071_ACA SALUD CASA CENTRAL",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "48539598",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "2008-09-01",' +
						'"edad": "11",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": null,' +
						'"actividad_nombre": null,' +
						'"titular_codigo": "69799/19",' +
						'"titular_apellidos": "LEDESMA ",' +
						'"titular_nombres": "ARIELITO",' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2008-09-01",' +
						'"fecha_alta_administrativa": "2008-09-01",' +
						'"fecha_alta": "2008-09-10",' +
						'"fecha_vigencia": "2011-01-01",' +
						'"cuit": null,' +
						'"sujeto_facturacion": "Falso",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69799",' +
						'"full_name": "LEDESMA MORENA"' +
					'}' +
				'],' +
				'"links": {' +
					'"first": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019?page=1",' +
					'"last": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019?page=2",' +
					'"prev": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019?page=1",' +
					'"next": null' +
				'},' +
				'"meta": {' +
					'"current_page": 2,' +
					'"from": 16,' +
					'"last_page": 2,' +
					'"path": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019",' +
					'"per_page": 15,' +
					'"to": 25,' +
					'"total": 25,' +
					'"allowed_filters": [],' +
					'"allowed_sorts": [],' +
					'"allowed_appends": [],' +
					'"allowed_fields": [],' +
					'"allowed_includes": [],' +
					'"default_includes": [],' +
					'"optional_get_vars": {' +
						'"sortBy": [],' +
						'"sortOrder": [' +
							'"asc",' +
							'"desc"' +
						'],' +
						'"pageSize": {' +
							'"0": "?pageSize=0",' +
							'"15": "?pageSize=15",' +
							'"50": "?pageSize=50",' +
							'"100": "?pageSize=100"' +
						'}' +
					'}' +
				'}' +
			'}';
	}
	public static String getFoundBajaAccounts () {
		return
			'{' +
				'"data": [' +
					'{' +
						'"rn": "1",' +
						'"afi_id": 140975,' +
						'"afi_id_tit": null,' +
						'"entidad": "69791",' +
						'"codigo": "69791/17",' +
						'"apellidos": "ESPINOSA GABRIEL ERNESTO",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "B",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "20173680",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1968-03-12",' +
						'"edad": "51",' +
						'"estado_civil": "C",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "EMPL",' +
						'"actividad_nombre": "EMPLEADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2017-07-01",' +
						'"cuit": "20201736804",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69791",' +
						'"mail": "vmartinez@bbe-sa.com.ar",' +
						'"provincia": "A",' +
						'"localidad": "1200",' +
						'"tipo_telefono": "TEL",' +
						'"fecha_baja": "2019-10-01 00:00:00",' +
						'"pais_codigo": "AR",' +
						'"full_name": "ESPINOSA GABRIEL ERNESTO"' +
					'},' +
					'{' +
						'"rn": "2",' +
						'"afi_id": 140976,' +
						'"afi_id_tit": null,' +
						'"entidad": "69792",' +
						'"codigo": "69792/16",' +
						'"apellidos": "SAVORETTI GABRIEL GERMAN",' +
						'"nombres": ".",' +
						'"pam": "V",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "B",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "22725723",' +
						'"sexo": "M",' +
						'"fecha_nacimiento": "1972-07-06",' +
						'"edad": "47",' +
						'"estado_civil": "S",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "EMPL",' +
						'"actividad_nombre": "EMPLEADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2017-07-01",' +
						'"cuit": "20227257238",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69792",' +
						'"full_name": "SAVORETTI GABRIEL GERMAN"' +
					'},' +
					'{' +
						'"rn": "3",' +
						'"afi_id": 140977,' +
						'"afi_id_tit": null,' +
						'"entidad": "69793",' +
						'"codigo": "69793/15",' +
						'"apellidos": "CRUCIANI SILVIA ELENA",' +
						'"nombres": ".",' +
						'"pam": "F",' +
						'"tipo_afiliado": "TIT",' +
						'"parentesco": null,' +
						'"tiene_alertas": "F",' +
						'"estado": "B",' +
						'"plan_codigo": "AS300",' +
						'"plan_nombre": "SUPERIOR AS300",' +
						'"modelo_plan_codigo": "AS300",' +
						'"modelo_plan_nombre": "SUPERIOR AS300",' +
						'"agencia_codigo": "650098",' +
						'"agencia_nombre": "650098_ACA SALUD SUC. ROSARIO",' +
						'"categoria_codigo": "GEN",' +
						'"categoria_nombre": "GENERICO",' +
						'"agrupacion_codigo": "OBLEMP",' +
						'"agrupacion_nombre": "AFILIADOS OBLIGATORIOS POR EMPRESA",' +
						'"agrupacion1_codigo": "MEN",' +
						'"agrupacion1_nombre": "AFILIADOS CON FACTURACION MENSUAL",' +
						'"agrupacion2_codigo": "OTROS",' +
						'"agrupacion2_nombre": "OTROS PAGOS DISTINTOS DE DEBITO AUTOMATICO",' +
						'"agrupacion3_codigo": "SC",' +
						'"agrupacion3_nombre": "SIN CARENCIAS",' +
						'"agrupacion4_codigo": null,' +
						'"agrupacion4_nombre": null,' +
						'"empresa_codigo": "600011",' +
						'"empresa_sucursal": "1",' +
						'"empresa_nombre": "ACA SALUD COOP.PRESTACION SERV. MEDICO ASIST.LTDA",' +
						'"empresa_sucursal_nombre": "ACA SALUD C.P.S.M.A.L. - PLANES AL PERSONAL",' +
						'"afiliacion": "Aporte Obligatorio",' +
						'"aporta": "Falso",' +
						'"obra_social_codigo": "640008",' +
						'"obra_social_nombre": "O.S.P.ACA",' +
						'"obra_social_ant_codigo": null,' +
						'"obra_social_ant_nombre": null,' +
						'"tipo_documento": "DNI",' +
						'"numero_documento": "14666853",' +
						'"sexo": "F",' +
						'"fecha_nacimiento": "1961-03-15",' +
						'"edad": "58",' +
						'"estado_civil": "P",' +
						'"codigo_1": "054",' +
						'"gentilicio": "ARGENTINO",' +
						'"actividad_codigo": "EMPL",' +
						'"actividad_nombre": "EMPLEADO",' +
						'"titular_codigo": null,' +
						'"titular_apellidos": null,' +
						'"titular_nombres": null,' +
						'"antiguedad_reconocida": "0",' +
						'"ultima_alta": "2002-09-01",' +
						'"fecha_alta_administrativa": "2002-09-01",' +
						'"fecha_alta": "2002-10-02",' +
						'"fecha_vigencia": "2017-07-01",' +
						'"cuit": "23146668534",' +
						'"sujeto_facturacion": "Verdadero",' +
						'"adherente": "Falso",' +
						'"tipo_baja_codigo": null,' +
						'"tipo_baja_nombre": null,' +
						'"motivo_de_baja": null,' +
						'"excedente": null,' +
						'"f_modif": "2019-12-17 00:00:00",' +
						'"entidad_codigo": "69793",' +
						'"full_name": "CRUCIANI SILVIA ELENA"' +
					'}' +
				'],' +
				'"links": {' +
					'"first": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019?page=1",' +
					'"last": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019?page=2",' +
					'"prev": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019?page=1",' +
					'"next": null' +
				'},' +
				'"meta": {' +
					'"current_page": 2,' +
					'"from": 16,' +
					'"last_page": 2,' +
					'"path": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/afiliados/17-12-2019",' +
					'"per_page": 15,' +
					'"to": 25,' +
					'"total": 25,' +
					'"allowed_filters": [],' +
					'"allowed_sorts": [],' +
					'"allowed_appends": [],' +
					'"allowed_fields": [],' +
					'"allowed_includes": [],' +
					'"default_includes": [],' +
					'"optional_get_vars": {' +
						'"sortBy": [],' +
						'"sortOrder": [' +
							'"asc",' +
							'"desc"' +
						'],' +
						'"pageSize": {' +
							'"0": "?pageSize=0",' +
							'"15": "?pageSize=15",' +
							'"50": "?pageSize=50",' +
							'"100": "?pageSize=100"' +
						'}' +
					'}' +
				'}' +
			'}';
	}
	public static String getError(){
		return
			'{' +
				'"data": {' +
					'"error": true,' +
					'"errors": [],' +
					'"errorType": "exception",' +
					'"httpCode": 404,' +
					'"message": "Formato de fecha inválido. El formato debe ser d-m-Y.",' +
					'"debug_message": [],' +
					'"exception": "NotFoundHttpException",' +
					'"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php",' +
					'"line": 964' +
				'}' +
			'}';
	}
}