public class WSBatchEfectorMock  {

	public static String getFound(){
		return '{'+
					'"data": ['+
						'{'+
							'"rn": "1",'+
							'"codigo": "700047",'+
							'"nombre": "ASOC. MEDICA DE ROSARIO",'+
							'"descripcion": "ROS-P-200100100 ASOC. MEDICA DE ROSARIO",'+
							'"es_prestador": "V",'+
							'"codigo_clase": "ASOMED",'+
							'"clase": "ASOCIACION MEDICA",'+
							'"categoria": null,'+
							'"egresado": null,'+
							'"fecha_titulo": null,'+
							'"estado_civil": null,'+
							'"fecha_nacimiento": null,'+
							'"observaciones": "REPACTADO SIN VTO.-",'+
							'"estado": "A",'+
							'"fecha_vigencia": "1970-01-01 00:00:00",'+
							'"cuit": "30528073146",'+
							'"obs_prestador": "CONVENIO PDF - ojo, con tto. de linfedema del Dr. Gersman, se procesa con modificadores",'+
							'"estado_prestador": "A",'+
							'"fecha_vigencia_prestador": "2002-06-01 00:00:00",'+
							'"fecha_alta": "2002-06-01 00:00:00",'+
							'"fecha_baja": null,'+
							'"motivo_baja": null,'+
							'"es_profesional": "F",'+
							'"f_modif": "2019-12-09 00:00:00",'+
							'"f_modif_pre": null'+
						'},'+
						'{'+
							'"rn": "2",'+
							'"codigo": "700616",'+
							'"nombre": "SANATORIO PARQUE",'+
							'"descripcion": "ROS-P-200800675 SANATORIO PARQUE S.A.",'+
							'"es_prestador": "V",'+
							'"codigo_clase": "CYS",'+
							'"clase": "CLINICAS Y SANATORIOS DIRECTOS",'+
							'"categoria": null,'+
							'"egresado": null,'+
							'"fecha_titulo": null,'+
							'"estado_civil": null,'+
							'"fecha_nacimiento": null,'+
							'"observaciones": "REPACTADO SIN VTO.-\\n9-4: SE QUITA CONDICION DE NO RETENCION EN I.B.\\nA PARTIR DE 8/02 SE AUTORIZA A FACTURAR EN FORMA QUINCENAL\\n01/2003: PRESENTA CERTIFICADO DE NO RETENCION EN I.B.",'+
							'"estado": "A",'+
							'"fecha_vigencia": "1970-01-01 00:00:00",'+
							'"cuit": "30546057328",'+
							'"obs_prestador": "13-08-2014 VISTO CON EDGARDO PARA ODONTOLOGICA CORRESPONDEN LOS VALORES DE ASOC. MUTUAL DE ESPEC. ODONTOLOGICAS DE ROSARIO",'+
							'"estado_prestador": "A",'+
							'"fecha_vigencia_prestador": "1970-01-01 00:00:00",'+
							'"fecha_alta": "1970-01-01 00:00:00",'+
							'"fecha_baja": null,'+
							'"motivo_baja": null,'+
							'"es_profesional": "F",'+
							'"f_modif": null,'+
							'"f_modif_pre": "2019-12-09 00:00:00"'+
						'},'+
						'{'+
							'"rn": "3",'+
							'"codigo": "700076",'+
							'"nombre": "SANATORIO AMERICANO",'+
							'"descripcion": "ROS-P-200800699 SANATORIO AMERICANO S.A.",'+
							'"es_prestador": "V",'+
							'"codigo_clase": "CYS",'+
							'"clase": "CLINICAS Y SANATORIOS DIRECTOS",'+
							'"categoria": null,'+
							'"egresado": null,'+
							'"fecha_titulo": null,'+
							'"estado_civil": null,'+
							'"fecha_nacimiento": null,'+
							'"observaciones": "REPACTADO SIN VTO.-\\nEXENTO EN I.B. AÑO 2002\\n20/2/03: Vº CON MARTA, NO LLEGO EL CERTIFICADO. RETENER.\\n24/9/03: ENVIAN CERTIFICADO I.B. (EXENTOS AÑO 2003).",'+
							'"estado": "A",'+
							'"fecha_vigencia": "1970-01-01 00:00:00",'+
							'"cuit": "33545883509",'+
							'"obs_prestador": "21-09-2017 se cargan valores de Kinesio ( solo con sistema de banda magnetica) // 25-08-2017 FALTA DEFINIR KINESIO, SE CARGO $ 1 PARA QUE PUEDAN AUTORIZAR ON LINE HASTA VER QUE SE RESUELVE",'+
							'"estado_prestador": "A",'+
							'"fecha_vigencia_prestador": "1970-01-01 00:00:00",'+
							'"fecha_alta": "1970-01-01 00:00:00",'+
							'"fecha_baja": null,'+
							'"motivo_baja": null,'+
							'"es_profesional": "F",'+
							'"f_modif": null,'+
							'"f_modif_pre": "2019-12-09 00:00:00"'+
						'},'+
						'{'+
							'"rn": "4",'+
							'"codigo": "700084",'+
							'"nombre": "CIBIC",'+
							'"descripcion": "ROS-P-200800256 CIBIC S.A.",'+
							'"es_prestador": "V",'+
							'"codigo_clase": "INST_BIOQ",'+
							'"clase": "INSTITUTO BIOQUIMICO",'+
							'"categoria": null,'+
							'"egresado": null,'+
							'"fecha_titulo": null,'+
							'"estado_civil": null,'+
							'"fecha_nacimiento": null,'+
							'"observaciones": "VTO. 30 DS.-\\nA PARTIR DE 8/02 SE AUTORIZA A FACTURAR EN FORMA QUINCENAL",'+
							'"estado": "A",'+
							'"fecha_vigencia": "1970-01-01 00:00:00",'+
							'"cuit": "30638974386",'+
							'"obs_prestador": "O.K. - OJO PRESTADOR ON-LINE( fax)!! - NBU**PRESENTO CERTIFICADO DE EXCLUSION IVA 10/09/12",'+
							'"estado_prestador": "A",'+
							'"fecha_vigencia_prestador": "1970-01-01 00:00:00",'+
							'"fecha_alta": "1970-01-01 00:00:00",'+
							'"fecha_baja": null,'+
							'"motivo_baja": null,'+
							'"es_profesional": "F",'+
							'"f_modif": "2019-12-09 00:00:00",'+
							'"f_modif_pre": null'+
						'}'+
					'],'+
					'"links": {'+
						'"first": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/efectores/09-12-2019?page=1",'+
						'"last": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/efectores/09-12-2019?page=1",'+
						'"prev": null,'+
						'"next": null'+
					'},'+
					'"meta": {'+
						'"current_page": 1,'+
						'"from": 1,'+
						'"last_page": 1,'+
						'"path": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/efectores/09-12-2019",'+
						'"per_page": 15,'+
						'"to": 4,'+
						'"total": 4,'+
						'"allowed_filters": ['+
							'"codigo",'+
							'"nombre",'+
							'"clase",'+
							'"cuit"'+
						'],'+
						'"allowed_sorts": [],'+
						'"allowed_appends": [],'+
						'"allowed_fields": [],'+
						'"allowed_includes": [],'+
						'"default_includes": [],'+
						'"optional_get_vars": {'+
							'"sortBy": [],'+
							'"sortOrder": ['+
								'"asc",'+
								'"desc"'+
							']'+
						'}'+
					'}'+
				'}';
	}

	public static String getFoundAndContinue(){
		return '{'+
					'"data": ['+
						'{'+
							'"rn": "1",'+
							'"codigo": "700050",'+
							'"nombre": "ASOC. MEDICA DE MENDOZA",'+
							'"descripcion": "ROS-P-200100100 ASOC. MEDICA DE ROSARIO",'+
							'"es_prestador": "V",'+
							'"codigo_clase": "ASOMED",'+
							'"clase": "ASOCIACION MEDICA",'+
							'"categoria": null,'+
							'"egresado": null,'+
							'"fecha_titulo": null,'+
							'"estado_civil": null,'+
							'"fecha_nacimiento": null,'+
							'"observaciones": "REPACTADO SIN VTO.-",'+
							'"estado": "A",'+
							'"fecha_vigencia": "1970-01-01 00:00:00",'+
							'"cuit": "30528073146",'+
							'"obs_prestador": "CONVENIO PDF - ojo, con tto. de linfedema del Dr. Gersman, se procesa con modificadores",'+
							'"estado_prestador": "A",'+
							'"fecha_vigencia_prestador": "2002-06-01 00:00:00",'+
							'"fecha_alta": "2002-06-01 00:00:00",'+
							'"fecha_baja": null,'+
							'"motivo_baja": null,'+
							'"es_profesional": "F",'+
							'"f_modif": "2019-12-09 00:00:00",'+
							'"f_modif_pre": null'+
						'}'+
						
					'],'+
					'"links": {'+
						'"first": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/efectores/09-12-2019?page=1",'+
						'"last": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/efectores/09-12-2019?page=1",'+
						'"prev": null,'+
						'"next": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/efectores/09-12-2019?page=1"'+
					'},'+
					'"meta": {'+
						'"current_page": 1,'+
						'"from": 1,'+
						'"last_page": 2,'+
						'"path": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/efectores/09-12-2019",'+
						'"per_page": 15,'+
						'"to": 4,'+
						'"total": 4,'+
						'"allowed_filters": ['+
							'"codigo",'+
							'"nombre",'+
							'"clase",'+
							'"cuit"'+
						'],'+
						'"allowed_sorts": [],'+
						'"allowed_appends": [],'+
						'"allowed_fields": [],'+
						'"allowed_includes": [],'+
						'"default_includes": [],'+
						'"optional_get_vars": {'+
							'"sortBy": [],'+
							'"sortOrder": ['+
								'"asc",'+
								'"desc"'+
							']'+
						'}'+
					'}'+
				'}';
	}

	public static String getError(){
		return '{'+
				'"data": {'+
					'"error": true,'+
					'"errors": [],'+
					'"errorType": "exception",'+
					'"httpCode": 404,'+
					'"message": "La ruta que está buscando no existe.",'+
					'"debug_message": [],'+
					'"exception": "NotFoundHttpException",'+
					'"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteCollection.php",'+
					'"line": 179'+
				'}'+
			'}';
	}

	public static String getEmpty(){
		return '{'+
				'"data": [],'+
				'"meta": {'+
					'"allowed_filters": [],'+
					'"allowed_sorts": [],'+
					'"allowed_appends": [],'+
					'"allowed_fields": [],'+
					'"allowed_includes": [],'+
					'"default_includes": [],'+
					'"optional_get_vars": {'+
						'"sortBy": [],'+
						'"sortOrder": ['+
							'"asc",'+
							'"desc"'+
						'],'+
						'"pageSize": {'+
							'"0": "?pageSize=0",'+
							'"15": "?pageSize=15",'+
							'"50": "?pageSize=50",'+
							'"100": "?pageSize=100"'+
						'}'+
					'}'+
				'}'+
			'}';
	}
}