@IsTest
public class WSBatchMedicamentosMock  {

	public static String getFound() {
		return
            '{' +
                '"data": [' +
                    '{' +
                        '"rn": "1",' +
                        '"accion_terapeutica": "412",' +
                        '"codigo": "51853",' +
                        '"nombre_producto": "NUTRAPLUS D",' +
                        '"nombre_presentacion": "CR.PROTECT.P/MANOS X50ML",' +
                        '"grupo": "MENCVL0001",' +
                        '"nombre_grupo": "MEDICAMENTOS VENTA LIBRE",' +
                        '"tipo_cober": "NO CUBIERTOS",' +
                        '"troquel": "9951853",' +
                        '"codigo_barras": "7612076460638",' +
                        '"codigo_externo_1": "51853",' +
                        '"codigo_externo_2": null,' +
                        '"codigo_externo_3": null,' +
                        '"medlab_codigo": "321",' +
                        '"tamano": "1",' +
                        '"descripcion": null,' +
                        '"medat_nombre": "DERMATOCOSMETICOS",' +
                        '"nombre_forma": "CREMAS/GELES/POMADAS/UNGUENTOS",' +
                        '"nombre_lab": "GALDERMA",' +
                        '"nombre_monodroga": "GLICERINA+ASOC.",' +
                        '"nombre_tam": "MENOR",' +
                        '"nombre_unidad": "NO CLASIFICADA",' +
                        '"nombre_tipouni": "UNIDADES DE 50 ML",' +
                        '"descrip_via": "USO EXTERNO",' +
                        '"edad_maxima": null,' +
                        '"edad_minima": null,' +
                        '"estado_informado": "B",' +
                        '"estado_presentacion": "B",' +
                        '"estado_vigencia": null,' +
                        '"excluye_vademecum": null,' +
                        '"fecha_activacion": "2015-11-10 00:00:00",' +
                        '"fecha_baja": "2019-01-09 00:00:00",' +
                        '"fecha_estado": "2019-01-09 00:00:00",' +
                        '"forma": "4",' +
                        '"grupo_terapeutico": null,' +
                        '"max_unidades": null,' +
                        '"med_bonificado": null,' +
                        '"medlab_codigo_1": "321",' +
                        '"monodroga": "M513",' +
                        '"nacional": "I",' +
                        '"nombre_forma_1": "CREMAS/GELES/POMADAS/UNGUENTOS",' +
                        '"nombre_monodroga_1": "GLICERINA+ASOC.",' +
                        '"nombre_tam_1": "MENOR",' +
                        '"tipo_uni": "24",' +
                        '"observaciones": null,' +
                        '"pmi_hijo": "F",' +
                        '"pmi_madre": "F",' +
                        '"potencia": null,' +
                        '"precio_referencia": null,' +
                        '"psicofarmaco": "F",' +
                        '"referencia_externa_2": null,' +
                        '"referencia_externa_3": null,' +
                        '"resol_310": null,' +
                        '"sexo_permitido": "A",' +
                        '"tama": "1",' +
                        '"unidades_divisibles": "1",' +
                        '"unidades_division": "1",' +
                        '"unidad": "1",' +
                        '"venta_libre": "V",' +
                        '"estupefaciente": "F"' +
                    '},' +
                    '{' +
                        '"rn": "2",' +
                        '"accion_terapeutica": "523",' +
                        '"codigo": "21038",' +
                        '"nombre_producto": "TOSCALMIN PEDIATRICO",' +
                        '"nombre_presentacion": "JBE.X 120 ML",' +
                        '"grupo": "MENCVL0001",' +
                        '"nombre_grupo": "MEDICAMENTOS VENTA LIBRE",' +
                        '"tipo_cober": "NO CUBIERTOS",' +
                        '"troquel": "9921038",' +
                        '"codigo_barras": "7798113690814",' +
                        '"codigo_externo_1": "21038",' +
                        '"codigo_externo_2": null,' +
                        '"codigo_externo_3": null,' +
                        '"medlab_codigo": "689",' +
                        '"tamano": "1",' +
                        '"descripcion": null,' +
                        '"medat_nombre": "EXPECTORANTE MUCOLITICO",' +
                        '"nombre_forma": "JARABE/SUSPENSION ORAL/POLVO PARA USO ORAL",' +
                        '"nombre_lab": "OMICRON",' +
                        '"nombre_monodroga": "BROMHEXINA",' +
                        '"nombre_tam": "MENOR",' +
                        '"nombre_unidad": "NO CLASIFICADA",' +
                        '"nombre_tipouni": "UNIDADES DE 120 ML",' +
                        '"descrip_via": "ORAL",' +
                        '"edad_maxima": null,' +
                        '"edad_minima": null,' +
                        '"estado_informado": "A",' +
                        '"estado_presentacion": "A",' +
                        '"estado_vigencia": null,' +
                        '"excluye_vademecum": null,' +
                        '"fecha_activacion": "2019-01-22 00:00:00",' +
                        '"fecha_baja": null,' +
                        '"fecha_estado": "2019-01-22 00:00:00",' +
                        '"forma": "10",' +
                        '"grupo_terapeutico": null,' +
                        '"max_unidades": null,' +
                        '"med_bonificado": null,' +
                        '"medlab_codigo_1": "689",' +
                        '"monodroga": "M1318",' +
                        '"nacional": "N",' +
                        '"nombre_forma_1": "JARABE/SUSPENSION ORAL/POLVO PARA USO ORAL",' +
                        '"nombre_monodroga_1": "BROMHEXINA",' +
                        '"nombre_tam_1": "MENOR",' +
                        '"tipo_uni": "43",' +
                        '"observaciones": null,' +
                        '"pmi_hijo": "F",' +
                        '"pmi_madre": "F",' +
                        '"potencia": "4",' +
                        '"precio_referencia": null,' +
                        '"psicofarmaco": "F",' +
                        '"referencia_externa_2": null,' +
                        '"referencia_externa_3": null,' +
                        '"resol_310": null,' +
                        '"sexo_permitido": "A",' +
                        '"tama": "1",' +
                        '"unidades_divisibles": "1",' +
                        '"unidades_division": "1",' +
                        '"unidad": "1",' +
                        '"venta_libre": "V",' +
                        '"estupefaciente": "F"' +
                    '}' +
                '],' +
                '"links": {' +
                    '"first": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/medicamentos/2019-01-01?page=1",' +
                    '"last": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/medicamentos/2019-01-01?page=17",' +
                    '"prev": null,' +
                    '"next": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/medicamentos/2019-01-01?page=2"' +
                '},' +
                '"meta": {' +
                    '"current_page": 1,' +
                    '"from": 1,' +
                    '"last_page": 2,' +
                    '"path": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/medicamentos/2019-01-01",' +
                    '"per_page": 15,' +
                    '"to": 15,' +
                    '"total": 254,' +
                    '"allowed_filters": [],' +
                    '"allowed_sorts": [],' +
                    '"allowed_appends": [],' +
                    '"allowed_fields": [],' +
                    '"allowed_includes": [],' +
                    '"default_includes": [],' +
                    '"optional_get_vars": {' +
                        '"sortBy": [],' +
                        '"sortOrder": [' +
                            '"asc",' +
                            '"desc"' +
                        '],' +
                        '"pageSize": {' +
                            '"0": "?pageSize=0",' +
                            '"15": "?pageSize=15",' +
                            '"50": "?pageSize=50",' +
                            '"100": "?pageSize=100"' +
                        '}' +
                    '}' +
                '}' +
            '}';
	}

	public static String getFoundSecondPage() {
		return
            '{' +
                '"data": [' +
                    '{' +
                        '"rn": "16",' +
                        '"accion_terapeutica": "407",' +
                        '"codigo": "44798",' +
                        '"nombre_producto": "GUM CEPILLOS ESPECIALIDADES",' +
                        '"nombre_presentacion": "125MH ORTHODONTIC 4 HIL.",' +
                        '"grupo": "MENCVL0001",' +
                        '"nombre_grupo": "MEDICAMENTOS VENTA LIBRE",' +
                        '"tipo_cober": "NO CUBIERTOS",' +
                        '"troquel": "9944798",' +
                        '"codigo_barras": "0070942501255",' +
                        '"codigo_externo_1": "44798",' +
                        '"codigo_externo_2": null,' +
                        '"codigo_externo_3": null,' +
                        '"medlab_codigo": "701",' +
                        '"tamano": "1",' +
                        '"descripcion": null,' +
                        '"medat_nombre": "PRODUCTOS ODONTOLOGICOS",' +
                        '"nombre_forma": "CEPILLOS DENTALES",' +
                        '"nombre_lab": "SUNSTAR",' +
                        '"nombre_monodroga": "ACCESORIO",' +
                        '"nombre_tam": "MENOR",' +
                        '"nombre_unidad": "NO CLASIFICADA",' +
                        '"nombre_tipouni": "UNIDADES",' +
                        '"descrip_via": "NO CLASIFICADA",' +
                        '"edad_maxima": null,' +
                        '"edad_minima": null,' +
                        '"estado_informado": "B",' +
                        '"estado_presentacion": "B",' +
                        '"estado_vigencia": null,' +
                        '"excluye_vademecum": null,' +
                        '"fecha_activacion": "2010-02-04 00:00:00",' +
                        '"fecha_baja": "2019-01-16 00:00:00",' +
                        '"fecha_estado": "2019-01-16 00:00:00",' +
                        '"forma": "35",' +
                        '"grupo_terapeutico": null,' +
                        '"max_unidades": null,' +
                        '"med_bonificado": null,' +
                        '"medlab_codigo_1": "701",' +
                        '"monodroga": "M10500",' +
                        '"nacional": "I",' +
                        '"nombre_forma_1": "CEPILLOS DENTALES",' +
                        '"nombre_monodroga_1": "ACCESORIO",' +
                        '"nombre_tam_1": "MENOR",' +
                        '"tipo_uni": "5",' +
                        '"observaciones": null,' +
                        '"pmi_hijo": "F",' +
                        '"pmi_madre": "F",' +
                        '"potencia": null,' +
                        '"precio_referencia": null,' +
                        '"psicofarmaco": "F",' +
                        '"referencia_externa_2": null,' +
                        '"referencia_externa_3": null,' +
                        '"resol_310": null,' +
                        '"sexo_permitido": "A",' +
                        '"tama": "1",' +
                        '"unidades_divisibles": "1",' +
                        '"unidades_division": "1",' +
                        '"unidad": "1",' +
                        '"venta_libre": "V",' +
                        '"estupefaciente": "F"' +
                    '},' +
                    '{' +
                        '"rn": "17",' +
                        '"accion_terapeutica": "346",' +
                        '"codigo": "39124",' +
                        '"nombre_producto": "CENTELLA + GINKGO + TRIGO SERRACENO",' +
                        '"nombre_presentacion": "BLIST.X 12 X 10 COMP.",' +
                        '"grupo": "MENCVL0001",' +
                        '"nombre_grupo": "MEDICAMENTOS VENTA LIBRE",' +
                        '"tipo_cober": "NO CUBIERTOS",' +
                        '"troquel": "9939124",' +
                        '"codigo_barras": null,' +
                        '"codigo_externo_1": "39124",' +
                        '"codigo_externo_2": null,' +
                        '"codigo_externo_3": null,' +
                        '"medlab_codigo": "583",' +
                        '"tamano": "1",' +
                        '"descripcion": null,' +
                        '"medat_nombre": "SUPLEMENTO DIETARIO",' +
                        '"nombre_forma": "COMPRIMIDOS/PASTILLAS/TABLETAS/GRAGEAS",' +
                        '"nombre_lab": "BIOKOSMA",' +
                        '"nombre_monodroga": "CENTELLA ASIATICA+ASOC.",' +
                        '"nombre_tam": "MENOR",' +
                        '"nombre_unidad": "NO CLASIFICADA",' +
                        '"nombre_tipouni": "UNIDADES",' +
                        '"descrip_via": "ORAL",' +
                        '"edad_maxima": null,' +
                        '"edad_minima": null,' +
                        '"estado_informado": "B",' +
                        '"estado_presentacion": "B",' +
                        '"estado_vigencia": null,' +
                        '"excluye_vademecum": null,' +
                        '"fecha_activacion": "2006-10-19 00:00:00",' +
                        '"fecha_baja": "2019-01-30 00:00:00",' +
                        '"fecha_estado": "2019-01-30 00:00:00",' +
                        '"forma": "54",' +
                        '"grupo_terapeutico": null,' +
                        '"max_unidades": null,' +
                        '"med_bonificado": null,' +
                        '"medlab_codigo_1": "583",' +
                        '"monodroga": "M249",' +
                        '"nacional": "N",' +
                        '"nombre_forma_1": "COMPRIMIDOS/PASTILLAS/TABLETAS/GRAGEAS",' +
                        '"nombre_monodroga_1": "CENTELLA ASIATICA+ASOC.",' +
                        '"nombre_tam_1": "MENOR",' +
                        '"tipo_uni": "5",' +
                        '"observaciones": null,' +
                        '"pmi_hijo": "F",' +
                        '"pmi_madre": "F",' +
                        '"potencia": null,' +
                        '"precio_referencia": null,' +
                        '"psicofarmaco": "F",' +
                        '"referencia_externa_2": null,' +
                        '"referencia_externa_3": null,' +
                        '"resol_310": null,' +
                        '"sexo_permitido": "A",' +
                        '"tama": "1",' +
                        '"unidades_divisibles": "10",' +
                        '"unidades_division": "1",' +
                        '"unidad": "1",' +
                        '"venta_libre": "V",' +
                        '"estupefaciente": "F"' +
                    '}' +
                '],' +
                '"links": {' +
                    '"first": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/medicamentos/2019-01-01?page=1",' +
                    '"last": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/medicamentos/2019-01-01?page=17",' +
                    '"prev": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/medicamentos/2019-01-01?page=1",' +
                    '"next": null' +
                '},' +
                '"meta": {' +
                    '"current_page": 2,' +
                    '"from": 16,' +
                    '"last_page": 2,' +
                    '"path": "https://api-test.acasalud.com.ar/aca_salud_test/public//v1/salud/batch/medicamentos/2019-01-01",' +
                    '"per_page": 15,' +
                    '"to": 30,' +
                    '"total": 254,' +
                    '"allowed_filters": [],' +
                    '"allowed_sorts": [],' +
                    '"allowed_appends": [],' +
                    '"allowed_fields": [],' +
                    '"allowed_includes": [],' +
                    '"default_includes": [],' +
                    '"optional_get_vars": {' +
                        '"sortBy": [],' +
                        '"sortOrder": [' +
                            '"asc",' +
                            '"desc"' +
                        '],' +
                        '"pageSize": {' +
                            '"0": "?pageSize=0",' +
                            '"15": "?pageSize=15",' +
                            '"50": "?pageSize=50",' +
                            '"100": "?pageSize=100"' +
                        '}' +
                    '}' +
                '}' +
            '}';
	}

	public static String getError(){
		return
            '{' +
                '"data": {' +
                    '"error": true,' +
                    '"errors": [],' +
                    '"errorType": "exception",' +
                    '"httpCode": 404,' +
                    '"message": "Formato de fecha inválido. El formato debe ser d-m-Y.",' +
                    '"debug_message": [],' +
                    '"exception": "NotFoundHttpException",' +
                    '"line": 964' +
                '}' +
            '}';
	}
}