public class WSCaseEnviarASSGenericResponse {

	/*public class Meta {
		public List<Notas> allowed_includes;
		public List<Notas> default_includes;
	}
	public class Data {
		
		public String sf_id;
		public String solafi_id;
		public String estado_sol;
		public String estado_dj;
		public String codigo_as;
		public String tipo_asoc;
		public String afi_id;
		public String empresa_codigo;
		public String suc_empresa;
		public List<Notas> notas;
	}

	public Boolean error;
	public List<Data> data;
	public Integer httpCode;
	public String message;
	public Meta meta;

	
	public static WSCaseEnviarASSGenericResponse parse(String json) {
		return (WSCaseEnviarASSGenericResponse) System.JSON.deserialize(json, WSCaseEnviarASSGenericResponse.class);
	}*/
}