public class WSEfectorGetEspecialidadesMock {


    public static String getFound(){
        return '{'+
                '"data": ['+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "538",'+
                '"descripcion": "CIRUGIA PLASTICA Y REPARADORA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "588",'+
                '"descripcion": "PSICOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "573",'+
                '"descripcion": "OBSTETRICIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "506",'+
                '"descripcion": "ENDOCRINOLOGIA Y METABOLISMO",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "505",'+
                '"descripcion": "DERMATOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "522",'+
                '"descripcion": "PSIQUIATRIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "516",'+
                '"descripcion": "OFTALMOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "501",'+
                '"descripcion": "ALERGIA E INMUNOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "502",'+
                '"descripcion": "ANATOMIA PATOLOGICA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "503",'+
                '"descripcion": "CARDIOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "504",'+
                '"descripcion": "CIRUGIA GENERAL",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "507",'+
                '"descripcion": "GASTROENTEROLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "508",'+
                '"descripcion": "GINECOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "509",'+
                '"descripcion": "HEMATOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "513",'+
                '"descripcion": "NEFROLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "514",'+
                '"descripcion": "NEUMONOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "515",'+
                '"descripcion": "NEUROCIRUGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "517",'+
                '"descripcion": "ONCOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "518",'+
                '"descripcion": "TRAUMATOLOGIA Y ORTOPEDIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "519",'+
                '"descripcion": "OTORRINOLARINGOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "520",'+
                '"descripcion": "PEDIATRIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "521",'+
                '"descripcion": "PROCTOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "524",'+
                '"descripcion": "UROLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "525",'+
                '"descripcion": "CLINICA MEDICA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "526",'+
                '"descripcion": "ECOGRAFIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "528",'+
                '"descripcion": "LABORATORIO DE ANALISIS CLINICOS",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "529",'+
                '"descripcion": "MEDICINA NUCLEAR",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "530",'+
                '"descripcion": "RADIOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "531",'+
                '"descripcion": "TOMOGRAFIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "533",'+
                '"descripcion": "DIAGNOSTICO POR IMAGENES",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "534",'+
                '"descripcion": "ANGIOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "536",'+
                '"descripcion": "CIRUGIA CARDIOVASCULAR",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "537",'+
                '"descripcion": "CIRUGIA INFANTIL",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "539",'+
                '"descripcion": "CIRUGIA TORACICA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "540",'+
                '"descripcion": "CITODIAGNOSTICO",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "555",'+
                '"descripcion": "HEMODINAMIA ADULTOS",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "556",'+
                '"descripcion": "OBSTETRICIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "558",'+
                '"descripcion": "CIRUGIA TRAUMATOLOGICA Y ORTOPEDICA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "564",'+
                '"descripcion": "CIRUGIA VASCULAR PERIFERICA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "565",'+
                '"descripcion": "CARDIOANGIOLOGIA CLINICA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "570",'+
                '"descripcion": "FLEBOLOGIA Y LINFOLOGIA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "568",'+
                '"descripcion": "MEDICINA GENERAL",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "_GM",'+
                '"descripcion": "GUARDIA MEDICA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "_GC",'+
                '"descripcion": "GUARDIA CARDIOLOGICA",'+
                '"aca_cartilla": "A"'+
                '},'+
                '{'+
                '"efector": "700616",'+
                '"nombre": "SANATORIO PARQUE",'+
                '"especialidad": "_I",'+
                '"descripcion": "INTERNACION",'+
                '"aca_cartilla": "A"'+
                '}'+
                '],'+
                '"meta": {'+
                '"allowed_filters": [],'+
                '"allowed_sorts": [],'+
                '"allowed_appends": [],'+
                '"allowed_fields": [],'+
                '"allowed_includes": [],'+
                '"default_includes": [],'+
                '"optional_get_vars": {'+
                '"sortBy": [],'+
                '"sortOrder": ['+
                '"asc",'+
                '"desc"'+
                '],'+
                '"pageSize": {'+
                '"0": "?pageSize=0",'+
                '"15": "?pageSize=15",'+
                '"50": "?pageSize=50",'+
                '"100": "?pageSize=100"'+
                '}'+
                '}'+
                '}'+
                '}';
    }

    public static String getEmpty(){
        return '{'+
                '"data": [],'+
                '"meta": {'+
                '"allowed_filters": [],'+
                '"allowed_sorts": [],'+
                '"allowed_appends": [],'+
                '"allowed_fields": [],'+
                '"allowed_includes": [],'+
                '"default_includes": [],'+
                '"optional_get_vars": {'+
                '"sortBy": [],'+
                '"sortOrder": ['+
                '"asc",'+
                '"desc"'+
                '],'+
                '"pageSize": {'+
                '"0": "?pageSize=0",'+
                '"15": "?pageSize=15",'+
                '"50": "?pageSize=50",'+
                '"100": "?pageSize=100"'+
                '}'+
                '}'+
                '}'+
                '}';
    }

	public static String getError() {
		return
			'{' +
				'"data": {' +
					'"error": true,' +
					'"errors": [],' +
					'"errorType": "exception",' +
					'"httpCode": 404,' +
					'"message": "La ruta que está buscando no existe.",' +
					'"debug_message": [],' +
					'"exception": "NotFoundHttpException",' +
					'"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteCollection.php",' +
					'"line": 179' +
				'}' +
			'}';
	}
}