public without sharing class WSLocalidadMock {
    /**public static String getFound() {
        return '{' +
                    '"data": [' +
                        '{' +
                            '"codigo_postal": "1077CFE",' +
                            '"loc_loc_id": "3640",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
            				'"or_zona_nombre": "CABA",'+
                            '"or_zona": "OR_01",' +
                            '"organizador": "USERTEST",' +
                            '"f_modif_loc": "2020-04-06",' +
                            '"f_modif_zn": "2020-04-06",' +
                            '"f_modif_or": "2020-04-06"' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1078CFE",' +
                            '"loc_loc_id": "3641",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": "2020-04-06",' +
                            '"f_modif_zn": "2020-04-06",' +
                            '"f_modif_or": "2020-04-06"' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1079CFE",' +
                            '"loc_loc_id": "3642",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1080CFE",' +
                            '"loc_loc_id": "3643",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1081CFE",' +
                            '"loc_loc_id": "3644",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1082CFE",' +
                            '"loc_loc_id": "3645",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1083CFE",' +
                            '"loc_loc_id": "3646",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1084CFE",' +
                            '"loc_loc_id": "3647",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1085CFE",' +
                            '"loc_loc_id": "3648",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1086CFE",' +
                            '"loc_loc_id": "3649",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1087CFE",' +
                            '"loc_loc_id": "3650",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1088CFE",' +
                            '"loc_loc_id": "3651",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1089CFE",' +
                            '"loc_loc_id": "3652",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1092CFE",' +
                            '"loc_loc_id": "3653",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1093CFE",' +
                            '"loc_loc_id": "3654",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1094CFE",' +
                            '"loc_loc_id": "3655",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1095CFE",' +
                            '"loc_loc_id": "3656",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1096CFE",' +
                            '"loc_loc_id": "3657",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1097CFE",' +
                            '"loc_loc_id": "3658",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1098CFE",' +
                            '"loc_loc_id": "3659",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1100CFE",' +
                            '"loc_loc_id": "3660",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1101CFE",' +
                            '"loc_loc_id": "3661",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1102CFE",' +
                            '"loc_loc_id": "3662",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1103CFE",' +
                            '"loc_loc_id": "3663",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1104CFE",' +
                            '"loc_loc_id": "3664",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1105CFE",' +
                            '"loc_loc_id": "3665",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1106CFE",' +
                            '"loc_loc_id": "3666",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1107CFE",' +
                            '"loc_loc_id": "3667",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1108CFE",' +
                            '"loc_loc_id": "3668",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1109CFE",' +
                            '"loc_loc_id": "3669",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1112CFE",' +
                            '"loc_loc_id": "3670",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1113CFE",' +
                            '"loc_loc_id": "3671",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1114CFE",' +
                            '"loc_loc_id": "3672",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1115CFE",' +
                            '"loc_loc_id": "3673",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1116CFE",' +
                            '"loc_loc_id": "3674",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1117CFE",' +
                            '"loc_loc_id": "3675",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1118CFE",' +
                            '"loc_loc_id": "3676",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1119CFE",' +
                            '"loc_loc_id": "3677",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1120CFE",' +
                            '"loc_loc_id": "3678",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1122CFE",' +
                            '"loc_loc_id": "3679",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1129CFE",' +
                            '"loc_loc_id": "3680",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1130CFE",' +
                            '"loc_loc_id": "3681",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1131CFE",' +
                            '"loc_loc_id": "3682",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1132CFE",' +
                            '"loc_loc_id": "3683",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1133CFE",' +
                            '"loc_loc_id": "3684",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1134CFE",' +
                            '"loc_loc_id": "3685",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1135CFE",' +
                            '"loc_loc_id": "3686",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1136CFE",' +
                            '"loc_loc_id": "3687",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1137CFE",' +
                            '"loc_loc_id": "3688",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '},' +
                        '{' +
                            '"codigo_postal": "1138CFE",' +
                            '"loc_loc_id": "3689",' +
                            '"localidad": "CAPITAL FEDERAL",' +
                            '"pcia_codigo": "C",' +
                            '"zn_zona": "ZN_3",' +
                            '"or_zona": "OR_01",' +
                            '"organizador": "ORMOHARRA",' +
                            '"f_modif_loc": null,' +
                            '"f_modif_zn": null,' +
                            '"f_modif_or": null' +
                        '}' +
                    '],' +
                    '"links": {' +
                        '"first": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas?page=1",' +
                        '"last": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas?page=470",' +
                        '"prev": null,' +
                        '"next": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas?page=2"' +
                    '},' +
                    '"meta": {' +
                        '"current_page": 1,' +
                        '"from": 1,' +
                        '"last_page": 470,' +
                        '"path": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas",' +
                        '"per_page": 50,' +
                        '"to": 50,' +
                        '"total": 23475,' +
                        '"allowed_filters": [' +
                            '"localidad",' +
                            '"localidad_id",' +
                            '"codigo_postal",' +
                            '"fecha_modificacion"' +
                        '],' +
                        '"allowed_sorts": [' +
                            '"codigo_postal",' +
                            '"localidad"' +
                        '],' +
                        '"allowed_appends": [],' +
                        '"allowed_fields": [],' +
                        '"allowed_includes": [],' +
                        '"default_includes": [],' +
                        '"optional_get_vars": {' +
                            '"sortBy": [' +
                                '"codigo_postal",' +
                                '"localidad"' +
                            '],' +
                            '"sortOrder": [' +
                                '"asc",' +
                                '"desc"' +
                            '],' +
                            '"pageSize": {' +
                                '"0": "?pageSize=0",' +
                                '"15": "?pageSize=15",' +
                                '"50": "?pageSize=50",' +
                                '"100": "?pageSize=100"' +
                            '}' +
                        '}' +
                    '}' +
    '}';
    }
    public static String getFound2(){
    	return '{' +
            '"data": [' +
                '{' +
                    '"codigo_postal": "1139CFE",' +
                    '"loc_loc_id": "3690",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "USERTEST2",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1141CFE",' +
                    '"loc_loc_id": "3691",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1142CFE",' +
                    '"loc_loc_id": "3692",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1143CFE",' +
                    '"loc_loc_id": "3693",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1144CFE",' +
                    '"loc_loc_id": "3694",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1145CFE",' +
                    '"loc_loc_id": "3695",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1146CFE",' +
                    '"loc_loc_id": "3696",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1147CFE",' +
                    '"loc_loc_id": "3697",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1148CFE",' +
                    '"loc_loc_id": "3698",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1149CFE",' +
                    '"loc_loc_id": "3699",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1150CFE",' +
                    '"loc_loc_id": "3700",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1151CFE",' +
                    '"loc_loc_id": "3701",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1152CFE",' +
                    '"loc_loc_id": "3702",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1153CFE",' +
                    '"loc_loc_id": "3703",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1154CFE",' +
                    '"loc_loc_id": "3704",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1155CFE",' +
                    '"loc_loc_id": "3705",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1156CFE",' +
                    '"loc_loc_id": "3706",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1157CFE",' +
                    '"loc_loc_id": "3707",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1158CFE",' +
                    '"loc_loc_id": "3708",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1159CFE",' +
                    '"loc_loc_id": "3709",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1160CFE",' +
                    '"loc_loc_id": "3710",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1161CFE",' +
                    '"loc_loc_id": "3711",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1162CFE",' +
                    '"loc_loc_id": "3712",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1163CFE",' +
                    '"loc_loc_id": "3713",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1164CFE",' +
                    '"loc_loc_id": "3714",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1165CFE",' +
                    '"loc_loc_id": "3715",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1166CFE",' +
                    '"loc_loc_id": "3716",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1167CFE",' +
                    '"loc_loc_id": "3717",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1168CFE",' +
                    '"loc_loc_id": "3718",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1169CFE",' +
                    '"loc_loc_id": "3719",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1171CFE",' +
                    '"loc_loc_id": "3720",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1172CFE",' +
                    '"loc_loc_id": "3721",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1173CFE",' +
                    '"loc_loc_id": "3722",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1175CFE",' +
                    '"loc_loc_id": "3723",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1176CFE",' +
                    '"loc_loc_id": "3724",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1177CFE",' +
                    '"loc_loc_id": "3725",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1178CFE",' +
                    '"loc_loc_id": "3726",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1179CFE",' +
                    '"loc_loc_id": "3727",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1180CFE",' +
                    '"loc_loc_id": "3728",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1181CFE",' +
                    '"loc_loc_id": "3729",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1182CFE",' +
                    '"loc_loc_id": "3730",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1183CFE",' +
                    '"loc_loc_id": "3731",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1184CFE",' +
                    '"loc_loc_id": "3732",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1185CFE",' +
                    '"loc_loc_id": "3733",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1186CFE",' +
                    '"loc_loc_id": "3734",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1187CFE",' +
                    '"loc_loc_id": "3735",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1188CFE",' +
                    '"loc_loc_id": "3736",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1189CFE",' +
                    '"loc_loc_id": "3737",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1190CFE",' +
                    '"loc_loc_id": "3738",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '},' +
                '{' +
                    '"codigo_postal": "1191CFE",' +
                    '"loc_loc_id": "3739",' +
                    '"localidad": "CAPITAL FEDERAL",' +
                    '"pcia_codigo": "C",' +
                    '"zn_zona": "ZN_3",' +
                    '"or_zona": "OR_01",' +
                    '"organizador": "ORMOHARRA",' +
                    '"f_modif_loc": null,' +
                    '"f_modif_zn": null,' +
                    '"f_modif_or": null' +
                '}' +
            '],' +
            '"links": {' +
                '"first": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas?page=1",' +
                '"last": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas?page=470",' +
                '"prev": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas?page=1",' +
                '"next": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas?page=3"' +
            '},' +
            '"meta": {' +
                '"current_page": 2,' +
                '"from": 51,' +
                '"last_page": 470,' +
                '"path": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas",' +
                '"per_page": 50,' +
                '"to": 100,' +
                '"total": 23475,' +
                '"allowed_filters": [' +
                    '"localidad",' +
                    '"localidad_id",' +
                    '"codigo_postal",' +
                    '"fecha_modificacion"' +
                '],' +
                '"allowed_sorts": [' +
                    '"codigo_postal",' +
                    '"localidad"' +
                '],' +
                '"allowed_appends": [],' +
                '"allowed_fields": [],' +
                '"allowed_includes": [],' +
                '"default_includes": [],' +
                '"optional_get_vars": {' +
                    '"sortBy": [' +
                        '"codigo_postal",' +
                        '"localidad"' +
                    '],' +
                    '"sortOrder": [' +
                        '"asc",' +
                        '"desc"' +
                    '],' +
                    '"pageSize": {' +
                        '"0": "?pageSize=0",' +
                        '"15": "?pageSize=15",' +
                        '"50": "?pageSize=50",' +
                        '"100": "?pageSize=100"' +
                    '}' +
                '}' +
            '}' +
        '}' ;
    }
    public static String getError(){
        return '{' +
                    '"data": {' +
                        '"error": true,' +
                        '"errors": [],' +
                        '"errorType": "exception",' +
                        '"httpCode": 404,' +
                        '"message": "La ruta que está buscando no existe.",' +
                        '"debug_message": [],' +
                        '"exception": "NotFoundHttpException",' +
                        '"file": "C:\\Apache24_64\\htdocs\\aca_salud_test\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteCollection.php",' +
                        '"line": 179' +
                    '}' +
                '}' ;
    }
    public static String getEmpty(){
        return '{' +
                    '"data": [],' +
                    '"links": {' +
                        '"first": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas?page=1",' +
                        '"last": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas?page=1",' +
                        '"prev": null,' +
                        '"next": null' +
                    '},' +
                    '"meta": {' +
                        '"current_page": 1,' +
                        '"from": null,' +
                        '"last_page": 1,' +
                        '"path": "https://api-test.acasalud.com.ar/aca_salud_test/public/v1/salud/localidades-zonas",' +
                        '"per_page": 500,' +
                        '"to": null,' +
                        '"total": 0,' +
                        '"allowed_filters": [],' +
                        '"allowed_sorts": [],' +
                        '"allowed_appends": [],' +
                        '"allowed_fields": [],' +
                        '"allowed_includes": [],' +
                        '"default_includes": [],' +
                        '"optional_get_vars": {' +
                            '"sortBy": [' +
                                '"codigo_postal",' +
                                '"localidad"' +
                            '],' +
                            '"sortOrder": [' +
                                '"asc",' +
                                '"desc"' +
                            '],' +
                            '"pageSize": {' +
                                '"0": "?pageSize=0",' +
                                '"15": "?pageSize=15",' +
                                '"50": "?pageSize=50",' +
                                '"100": "?pageSize=100"' +
                            '}' +
                        '}' +
                    '}' +
                '}' ;
    }*/
}